# ================================================
# SEED_QUESTIONS_BATCH5.PY — Etape 4 FINAL — Sous-lot 2/2
# Usage : python manage.py seed_questions_batch5
# 75 questions (25 par module) — complète la banque à 300/300
# ================================================

from django.core.management.base import BaseCommand
from academie.models_banque import ModuleBanque, CategorieBanque, QuestionBanque


QUESTIONS_INTERNET = [
    {'categorie': 'Navigation Web', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Que permet un moteur de recherche interne à un site (barre de recherche du site) que Google ne fait pas toujours bien ?", 'reponses': [{'texte': 'Trouver des contenus spécifiques non indexés publiquement ou classer selon la logique propre du site', 'correct': True}, {'texte': 'Rien de différent de Google', 'correct': False}, {'texte': 'Bloquer les publicités', 'correct': False}, {'texte': 'Accélérer Internet', 'correct': False}], 'explication': "Un moteur de recherche interne accède parfois à du contenu non indexé par Google (pages récentes, contenu privé) et applique une logique de pertinence propre au site, complémentaire à la recherche externe.", 'mots_cles': 'recherche interne, moteur site'},
    {'categorie': 'Navigation Web', 'niveau': 'professionnel', 'type': 'qcm', 'enonce': "Quelle est la différence fondamentale entre le web « surface » et le « deep web » ?", 'reponses': [{'texte': 'Le deep web regroupe les pages non indexées par les moteurs de recherche classiques (bases de données privées, intranets)', 'correct': True}, {'texte': 'Le deep web est toujours illégal', 'correct': False}, {'texte': 'Il n\'y a aucune différence', 'correct': False}, {'texte': 'Le deep web n\'existe pas réellement', 'correct': False}], 'explication': "Le « deep web » désigne simplement tout contenu non indexé par les moteurs de recherche classiques (comptes bancaires en ligne, bases de données universitaires, intranets) — la grande majorité est parfaitement légale, à ne pas confondre avec le « dark web ».", 'mots_cles': 'deep web, indexation, distinction terminologique'},
    {'categorie': 'Recherche avancée', 'niveau': 'facile', 'type': 'vrai_faux', 'enonce': "Le premier résultat d'une recherche Google est toujours la source la plus fiable.", 'reponses': [{'texte': 'Vrai', 'correct': False}, {'texte': 'Faux', 'correct': True}], 'explication': "C'est faux : le classement Google prend en compte de nombreux facteurs (SEO, popularité, publicité) qui ne garantissent pas la fiabilité du contenu. L'esprit critique et la vérification de la source restent indispensables.", 'mots_cles': 'esprit critique, classement Google, fiabilité'},
    {'categorie': 'Opérateurs de recherche', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Quel opérateur permet de trouver des pages similaires à un site donné ?", 'reponses': [{'texte': 'related:nomdusite.com', 'correct': True}, {'texte': 'similar:nomdusite.com', 'correct': False}, {'texte': 'like:nomdusite.com', 'correct': False}, {'texte': 'copy:nomdusite.com', 'correct': False}], 'explication': "L'opérateur « related: » (moins fiable aujourd'hui mais toujours documenté) tente de trouver des sites au contenu ou à la thématique similaire à celui spécifié.", 'mots_cles': 'related, opérateur similarité'},
    {'categorie': 'Sécurité numérique', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Pourquoi éviter de se connecter à des services sensibles (banque) via un Wi-Fi public non sécurisé ?", 'reponses': [{'texte': 'Les données échangées peuvent être interceptées par d\'autres utilisateurs du même réseau', 'correct': True}, {'texte': 'Le Wi-Fi public est toujours plus lent, sans autre risque', 'correct': False}, {'texte': 'Cela n\'a aucun impact sur la sécurité', 'correct': False}, {'texte': 'C\'est interdit par la loi partout', 'correct': False}], 'explication': "Sur un réseau Wi-Fi public non sécurisé, des tiers malveillants peuvent potentiellement intercepter le trafic non chiffré — d'où l'importance d'utiliser un VPN ou d'éviter les transactions sensibles sur ces réseaux.", 'mots_cles': 'Wi-Fi public, interception données, précaution'},
    {'categorie': 'Sécurité numérique', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Que désigne le terme « ingénierie sociale » en cybersécurité ?", 'reponses': [{'texte': 'La manipulation psychologique d\'une personne pour obtenir des informations confidentielles', 'correct': True}, {'texte': 'Une technique de programmation avancée', 'correct': False}, {'texte': 'Un type de réseau social professionnel', 'correct': False}, {'texte': 'Un logiciel antivirus', 'correct': False}], 'explication': "L'ingénierie sociale exploite la psychologie humaine (urgence, confiance, autorité) plutôt que des failles techniques pour obtenir des informations sensibles — le phishing en est une forme courante.", 'mots_cles': 'ingénierie sociale, manipulation, cybersécurité'},
    {'categorie': 'Sécurité numérique', 'niveau': 'professionnel', 'type': 'etude_cas', 'enonce': "Un employé reçoit un appel d'une personne se faisant passer pour son « nouveau responsable IT », demandant son mot de passe pour « une maintenance urgente ». Quelle règle de sécurité fondamentale s'applique ici ?", 'reponses': [{'texte': 'Aucun service IT légitime ne demande jamais un mot de passe directement — refuser et vérifier via un canal officiel connu', 'correct': True}, {'texte': 'Donner le mot de passe car c\'est urgent', 'correct': False}, {'texte': 'Donner un mot de passe légèrement modifié', 'correct': False}, {'texte': 'Demander au collègue de le faire à sa place', 'correct': False}], 'explication': "Règle absolue de sécurité informatique : aucun service IT légitime ne demande jamais un mot de passe par téléphone ou email. Cette demande est un signal d'alerte classique d'ingénierie sociale — toujours vérifier l'identité via un canal officiel indépendant.", 'mots_cles': 'demande mot de passe, ingénierie sociale, règle absolue'},
    {'categorie': 'Google Workspace', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Quelle application Google Workspace permet de prendre des notes rapides et de créer des rappels ?", 'reponses': [{'texte': 'Google Keep', 'correct': True}, {'texte': 'Google Slides', 'correct': False}, {'texte': 'Google Meet', 'correct': False}, {'texte': 'Google Sheets', 'correct': False}], 'explication': "Google Keep est une application de prise de notes rapide, intégrée à l'écosystème Google Workspace, idéale pour des rappels et listes courtes accessibles partout.", 'mots_cles': 'Google Keep, notes rapides, productivité'},
    {'categorie': 'Organisation des fichiers', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Que se passe-t-il généralement quand on déplace un fichier vers la corbeille sans la vider ?", 'reponses': [{'texte': 'Le fichier reste récupérable jusqu\'à ce que la corbeille soit vidée', 'correct': True}, {'texte': 'Le fichier est supprimé définitivement immédiatement', 'correct': False}, {'texte': 'Le fichier est envoyé automatiquement par email', 'correct': False}, {'texte': 'Rien ne se passe', 'correct': False}], 'explication': "La corbeille offre une sécurité de récupération temporaire — le fichier n'est réellement supprimé qu'après avoir explicitement vidé la corbeille (ou après un délai automatique sur certains systèmes cloud).", 'mots_cles': 'corbeille, suppression, récupération fichier'},
    {'categorie': 'Collaboration', 'niveau': 'professionnel', 'type': 'qcm', 'enonce': "Pourquoi documenter les décisions prises lors d'une réunion (compte-rendu) est-il important en contexte professionnel ?", 'reponses': [{'texte': 'Garantir une trace claire, éviter les malentendus et permettre le suivi des actions décidées', 'correct': True}, {'texte': 'C\'est une perte de temps inutile', 'correct': False}, {'texte': 'Uniquement pour respecter une formalité sans valeur', 'correct': False}, {'texte': 'Cela n\'a aucun impact sur le travail d\'équipe', 'correct': False}], 'explication': "Un compte-rendu de réunion documente les décisions, responsabilités et échéances — évitant les malentendus futurs et permettant un suivi clair des engagements pris collectivement.", 'mots_cles': 'compte-rendu, traçabilité décisions, professionnalisme'},
    {'categorie': 'Productivité', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Que signifie l'acronyme « GTD », une méthode populaire de gestion des tâches ?", 'reponses': [{'texte': 'Getting Things Done', 'correct': True}, {'texte': 'Global Task Directory', 'correct': False}, {'texte': 'General Time Distribution', 'correct': False}, {'texte': 'Group Task Delegation', 'correct': False}], 'explication': "GTD (Getting Things Done), méthode créée par David Allen, consiste à capturer toutes ses tâches dans un système externe fiable pour libérer l'esprit et organiser le travail par contexte et priorité.", 'mots_cles': 'GTD, méthode organisation, gestion tâches'},
    {'categorie': 'Recherche avancée', 'niveau': 'professionnel', 'type': 'scenario_pro', 'enonce': "Vous devez identifier la source originale d'une citation virale circulant sur les réseaux sociaux, potentiellement mal attribuée. Quelle démarche de vérification suivre ?", 'reponses': [{'texte': 'Rechercher la citation exacte entre guillemets, croiser avec des sites de vérification de faits (fact-checking) reconnus', 'correct': True}, {'texte': 'Faire confiance au premier partage vu', 'correct': False}, {'texte': 'Republier sans vérifier car c\'est viral', 'correct': False}, {'texte': 'Ignorer la question de la source', 'correct': False}], 'explication': "La recherche entre guillemets pour une citation exacte, croisée avec des sites de fact-checking reconnus (AFP Factuel, etc.), est la démarche professionnelle standard pour vérifier l'authenticité et l'attribution d'une citation virale.", 'mots_cles': 'fact-checking, vérification citation, méthode professionnelle'},
    {'categorie': 'Google Workspace', 'niveau': 'professionnel', 'type': 'qcm', 'enonce': "Comment restreindre le partage d'un document Google Drive pour qu'il ne soit accessible qu'aux personnes du domaine de l'entreprise (ex: @blessytechacademy.com) ?", 'reponses': [{'texte': 'Choisir l\'option de partage restreinte au domaine dans les paramètres de partage', 'correct': True}, {'texte': 'Rendre le document totalement public', 'correct': False}, {'texte': 'Ce n\'est techniquement pas possible', 'correct': False}, {'texte': 'Envoyer le lien uniquement par SMS', 'correct': False}], 'explication': "Google Workspace permet de restreindre le partage à un domaine organisationnel spécifique — une option intermédiaire entre « privé » et « public », adaptée à la collaboration interne sécurisée.", 'mots_cles': 'partage domaine, sécurité organisationnelle, Google Workspace'},
    {'categorie': 'Navigation Web', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quel bouton du navigateur permet de revenir à la page précédemment consultée ?", 'reponses': [{'texte': 'La flèche « Précédent » (retour)', 'correct': True}, {'texte': 'Le bouton Actualiser', 'correct': False}, {'texte': 'Le bouton Étoile (favoris)', 'correct': False}, {'texte': 'Le bouton Impression', 'correct': False}], 'explication': "La flèche « Précédent » (généralement en haut à gauche) navigue vers la page visitée juste avant, un élément fondamental de navigation web.", 'mots_cles': 'navigation de base, bouton précédent'},
    {'categorie': 'Sécurité numérique', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Pourquoi ne pas se déconnecter d'un compte utilisé sur un ordinateur public (cybercafé) est-il risqué ?", 'reponses': [{'texte': 'La prochaine personne utilisant l\'ordinateur pourrait accéder au compte resté connecté', 'correct': True}, {'texte': 'Aucun risque réel', 'correct': False}, {'texte': 'Cela ralentit uniquement l\'ordinateur', 'correct': False}, {'texte': 'Cela consomme plus de batterie', 'correct': False}], 'explication': "Ne pas se déconnecter sur un ordinateur partagé/public laisse le compte accessible à quiconque l'utilise ensuite — toujours se déconnecter explicitement et effacer l'historique/cookies sur un appareil non personnel.", 'mots_cles': 'déconnexion, ordinateur public, sécurité de base'},
    {'categorie': 'Productivité', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Quel est l'intérêt de créer des filtres/règles automatiques dans une boîte email professionnelle ?", 'reponses': [{'texte': 'Classer automatiquement les emails entrants selon des critères, réduisant l\'encombrement de la boîte de réception', 'correct': True}, {'texte': 'Supprimer tous les emails automatiquement', 'correct': False}, {'texte': 'Cela n\'a aucun effet réel', 'correct': False}, {'texte': 'Envoyer des emails automatiquement sans contrôle', 'correct': False}], 'explication': "Les filtres/règles email (par expéditeur, mot-clé, objet) trient automatiquement les messages entrants dans des dossiers appropriés, réduisant le bruit dans la boîte de réception principale et améliorant la gestion du flux d'informations.", 'mots_cles': 'filtres email, automatisation boîte de réception, organisation'},
    {'categorie': 'Collaboration', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quel est l'avantage de partager un lien de fichier plutôt que d'envoyer le fichier en pièce jointe par email ?", 'reponses': [{'texte': 'Tout le monde accède à la même version à jour, sans multiplier les copies', 'correct': True}, {'texte': 'C\'est toujours plus lent', 'correct': False}, {'texte': 'Aucun avantage', 'correct': False}, {'texte': 'Cela supprime le fichier original', 'correct': False}], 'explication': "Partager un lien vers un fichier cloud garantit que tous les collaborateurs consultent LA MÊME version actualisée, évitant la confusion classique des multiples pièces jointes de versions différentes du même document.", 'mots_cles': 'partage lien vs pièce jointe, version unique'},
]

QUESTIONS_IA = [
    {'categorie': 'Fondamentaux', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Quelle affirmation décrit correctement les « données d'entraînement » d'une IA ?", 'reponses': [{'texte': 'Un vaste ensemble d\'exemples utilisés pour apprendre à l\'IA à reconnaître des motifs', 'correct': True}, {'texte': 'Des instructions codées manuellement pour chaque réponse possible', 'correct': False}, {'texte': 'Un type de virus informatique', 'correct': False}, {'texte': 'Un mot de passe requis pour utiliser l\'IA', 'correct': False}], 'explication': "Les données d'entraînement sont l'immense corpus d'exemples (textes, images) sur lequel un modèle d'IA « apprend » à reconnaître des motifs statistiques, formant la base de ses capacités futures.", 'mots_cles': 'données entraînement, apprentissage IA'},
    {'categorie': 'IA générative', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Pourquoi certaines IA génératives ont-elles une « date de connaissance limite » (knowledge cutoff) ?", 'reponses': [{'texte': 'Leurs données d\'entraînement s\'arrêtent à une date précise, elles n\'ont pas connaissance des événements postérieurs sans outil de recherche', 'correct': True}, {'texte': 'C\'est une limite technique impossible à contourner', 'correct': False}, {'texte': 'Cela n\'existe pas réellement', 'correct': False}, {'texte': 'C\'est uniquement lié au prix de l\'abonnement', 'correct': False}], 'explication': "Une IA générative est entraînée sur des données jusqu'à une date donnée — au-delà, elle n'a aucune connaissance des événements récents, sauf si elle dispose d'un outil de recherche web intégré pour compléter ses connaissances.", 'mots_cles': 'date limite connaissance, entraînement, limites temporelles'},
    {'categorie': 'Prompt Engineering', 'niveau': 'facile', 'type': 'vrai_faux', 'enonce': "Reformuler un prompt après une réponse insatisfaisante est une pratique normale et recommandée.", 'reponses': [{'texte': 'Vrai', 'correct': True}, {'texte': 'Faux', 'correct': False}], 'explication': "L'itération (essayer, ajuster, reformuler) fait partie intégrante d'un usage efficace des IA génératives — il est tout à fait normal de ne pas obtenir la réponse idéale du premier coup.", 'mots_cles': 'itération prompt, amélioration continue'},
    {'categorie': 'Prompt Engineering', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Que désigne la technique du « zero-shot prompting » ?", 'reponses': [{'texte': 'Demander une tâche à l\'IA sans lui fournir aucun exemple préalable', 'correct': True}, {'texte': 'Fournir zéro information dans le prompt', 'correct': False}, {'texte': 'Une technique qui ne fonctionne jamais', 'correct': False}, {'texte': 'Une méthode de sécurité informatique', 'correct': False}], 'explication': "Le « zero-shot prompting » consiste à demander directement une tâche sans exemple préalable — à l'inverse du « few-shot » qui fournit des exemples. Les IA modernes performent souvent bien même en zero-shot pour des tâches courantes.", 'mots_cles': 'zero-shot, technique prompt, terminologie avancée'},
    {'categorie': 'Éthique', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Pourquoi est-il important de savoir qu'une image ou vidéo peut être un « deepfake » généré par IA ?", 'reponses': [{'texte': 'Pour développer un esprit critique face à un contenu qui pourrait sembler authentique mais être entièrement fabriqué', 'correct': True}, {'texte': 'Ce n\'est pas important', 'correct': False}, {'texte': 'Les deepfakes n\'existent pas réellement', 'correct': False}, {'texte': 'Seuls les experts doivent s\'en soucier', 'correct': False}], 'explication': "Un deepfake est un contenu (vidéo, audio, image) synthétique généré par IA, pouvant imiter de façon très convaincante une personne réelle. Une vigilance générale sur l'authenticité des contenus visuels/audio est de plus en plus nécessaire.", 'mots_cles': 'deepfake, esprit critique, désinformation'},
    {'categorie': 'Éthique', 'niveau': 'professionnel', 'type': 'etude_cas', 'enonce': "Une entreprise envisage de remplacer 5 postes administratifs par un système d'automatisation IA. Quelle démarche est éthiquement recommandée envers les employés concernés ?", 'reponses': [{'texte': 'Communiquer en amont, envisager la reconversion/formation vers d\'autres postes plutôt qu\'une suppression brutale', 'correct': True}, {'texte': 'Ne rien dire jusqu\'au dernier moment', 'correct': False}, {'texte': 'Licencier immédiatement sans préavis', 'correct': False}, {'texte': 'Ignorer complètement l\'impact humain', 'correct': False}], 'explication': "L'automatisation de postes soulève des enjeux éthiques et sociaux importants — une approche responsable privilégie la transparence, l'anticipation et l'accompagnement (formation, reconversion) plutôt qu'une rupture brutale sans considération humaine.", 'mots_cles': 'impact social IA, reconversion, éthique organisationnelle'},
    {'categorie': 'Vérification des réponses', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quelle est la meilleure attitude générale à adopter face à une réponse d'IA sur un sujet que vous ne maîtrisez pas ?", 'reponses': [{'texte': 'Rester prudent et vérifier avant de considérer l\'information comme acquise', 'correct': True}, {'texte': 'Accepter automatiquement toute réponse', 'correct': False}, {'texte': 'Rejeter systématiquement toute réponse IA', 'correct': False}, {'texte': 'Ne jamais utiliser l\'IA pour ce sujet', 'correct': False}], 'explication': "L'attitude équilibrée consiste ni à rejeter systématiquement ni à accepter aveuglément, mais à utiliser l'IA comme point de départ à vérifier — particulièrement important sur des sujets où l'on manque soi-même de repères pour juger.", 'mots_cles': 'esprit critique équilibré, vérification systématique'},
    {'categorie': 'Cas professionnels', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Comment l'IA peut-elle contribuer à améliorer l'accessibilité numérique (personnes malvoyantes, etc.) ?", 'reponses': [{'texte': 'Génération de descriptions d\'images automatiques (texte alternatif) et synthèse vocale améliorée', 'correct': True}, {'texte': 'L\'IA ne peut rien apporter dans ce domaine', 'correct': False}, {'texte': 'Uniquement pour créer des divertissements', 'correct': False}, {'texte': 'L\'IA rend toujours moins accessible', 'correct': False}], 'explication': "L'IA améliore concrètement l'accessibilité numérique : description automatique d'images pour lecteurs d'écran, sous-titrage automatique, synthèse vocale plus naturelle — un impact social positif souvent sous-estimé.", 'mots_cles': 'accessibilité numérique, IA sociale, impact positif'},
    {'categorie': 'Automatisation', 'niveau': 'professionnel', 'type': 'qcm', 'enonce': "Quel principe de gouvernance est recommandé avant de déployer une automatisation IA affectant directement les clients (ex: chatbot de réclamation) ?", 'reponses': [{'texte': 'Tester en phase pilote, prévoir un mécanisme d\'escalade vers un humain, et surveiller les retours', 'correct': True}, {'texte': 'Déployer directement à 100% sans test', 'correct': False}, {'texte': 'Aucune surveillance n\'est nécessaire après déploiement', 'correct': False}, {'texte': 'Empêcher tout contact humain définitivement', 'correct': False}], 'explication': "Une automatisation touchant directement les clients devrait suivre une démarche progressive : test pilote, mécanisme de secours humain pour les cas non résolus, et monitoring continu — exactement la même logique méthodique appliquée à cette banque de questions elle-même.", 'mots_cles': 'gouvernance IA, déploiement progressif, mécanisme escalade'},
    {'categorie': 'Fondamentaux', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Quelle affirmation est correcte concernant les limites actuelles de l'IA générative ?", 'reponses': [{'texte': 'Elle peut halluciner, manquer de jugement contextuel profond et refléter les biais de ses données d\'entraînement', 'correct': True}, {'texte': 'Elle est totalement infaillible dans tous les domaines', 'correct': False}, {'texte': 'Elle remplace intégralement le jugement humain sans exception', 'correct': False}, {'texte': 'Elle n\'a strictement aucune limite connue', 'correct': False}], 'explication': "Malgré des progrès impressionnants, l'IA générative actuelle présente des limites réelles et documentées : hallucinations, biais hérités des données, absence de compréhension profonde du contexte — une compréhension équilibrée de ces limites est essentielle pour un usage professionnel responsable.", 'mots_cles': 'limites IA, compréhension équilibrée, usage responsable'},
    {'categorie': 'IA générative', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quel usage NE relève PAS d'une IA générative de texte ?", 'reponses': [{'texte': 'Calculer automatiquement une moyenne dans un tableur (fonction native)', 'correct': True}, {'texte': 'Rédiger un brouillon d\'email', 'correct': False}, {'texte': 'Résumer un long document', 'correct': False}, {'texte': 'Corriger la grammaire d\'un texte', 'correct': False}], 'explication': "Une simple fonction de calcul dans un tableur (comme =MOYENNE()) est une fonction déterministe classique, pas de l'IA générative — bien distinguer les deux évite une confusion fréquente sur ce que « fait » réellement l'IA.", 'mots_cles': 'distinction fonction classique vs IA'},
    {'categorie': 'Vérification des réponses', 'niveau': 'avance', 'type': 'scenario_pro', 'enonce': "Un collègue partage un article prétendument généré et vérifié par IA affirmant un fait surprenant sur l'économie haïtienne. Quelle question devriez-vous vous poser en priorité avant de le croire ?", 'reponses': [{'texte': '« Quelle est la source primaire citée, et est-elle vérifiable indépendamment ? »', 'correct': True}, {'texte': '« Est-ce que l\'article est bien écrit ? »', 'correct': False}, {'texte': '« Combien de personnes l\'ont partagé ? »', 'correct': False}, {'texte': '« Est-ce que ça semble intéressant ? »', 'correct': False}], 'explication': "La qualité rédactionnelle ou la popularité d'un partage ne disent rien sur l'exactitude d'un fait. La question centrale de vérification reste toujours : existe-t-il une source primaire vérifiable et indépendante appuyant l'affirmation ?", 'mots_cles': 'source primaire, esprit critique avancé, vérification'},
]

QUESTIONS_BUREAUTIQUE = [
    {'categorie': 'Microsoft Word', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quel raccourci permet de sélectionner un mot entier en double-cliquant dessus ?", 'reponses': [{'texte': 'Double-clic gauche sur le mot', 'correct': True}, {'texte': 'Triple-clic', 'correct': False}, {'texte': 'Clic droit uniquement', 'correct': False}, {'texte': 'Molette de la souris', 'correct': False}], 'explication': "Un double-clic sur un mot le sélectionne entièrement — un triple-clic sélectionne généralement le paragraphe entier dans la plupart des logiciels de traitement de texte.", 'mots_cles': 'sélection mot, souris, Word de base'},
    {'categorie': 'Microsoft Word', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Quelle fonctionnalité Word permet de créer automatiquement une liste de références bibliographiques ?", 'reponses': [{'texte': 'Références > Citations et bibliographie', 'correct': True}, {'texte': 'Insertion > Zone de texte', 'correct': False}, {'texte': 'Accueil > Styles', 'correct': False}, {'texte': 'Ce n\'est pas possible dans Word', 'correct': False}], 'explication': "L'onglet Références propose un gestionnaire de citations et de bibliographie intégré, générant automatiquement une liste formatée selon différents styles académiques (APA, MLA, etc.).", 'mots_cles': 'bibliographie, citations, Word académique'},
    {'categorie': 'Microsoft Excel', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quel symbole permet de figer une référence de colonne dans une formule Excel (ex: $A1) ?", 'reponses': [{'texte': 'Le symbole $', 'correct': True}, {'texte': 'Le symbole #', 'correct': False}, {'texte': 'Le symbole %', 'correct': False}, {'texte': 'Le symbole &', 'correct': False}], 'explication': "Le symbole $ placé avant la lettre de colonne (ou le numéro de ligne) fige cette partie de la référence, l'empêchant de changer lors de la copie de la formule.", 'mots_cles': 'symbole dollar, référence figée, Excel de base'},
    {'categorie': 'Microsoft Excel', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Quelle fonction Excel additionne uniquement les cellules répondant à une condition (ex: total des ventes > 1000) ?", 'reponses': [{'texte': 'SOMME.SI', 'correct': True}, {'texte': 'NB.SI', 'correct': False}, {'texte': 'MOYENNE', 'correct': False}, {'texte': 'RECHERCHEV', 'correct': False}], 'explication': "SOMME.SI (SUMIF) additionne uniquement les valeurs répondant à un critère spécifié — complémentaire à NB.SI qui, elle, compte le nombre de cellules répondant au critère plutôt que d'en additionner les valeurs.", 'mots_cles': 'SOMME.SI, SUMIF, formule conditionnelle'},
    {'categorie': 'Microsoft Excel', 'niveau': 'professionnel', 'type': 'analyse_excel', 'enonce': "Un fichier Excel de 5000 lignes devient très lent à ouvrir et calculer. Quelle cause fréquente et solution recommandez-vous en priorité ?", 'reponses': [{'texte': 'Formules volatiles ou références à des plages entières de colonnes (ex: A:A) — limiter les plages aux besoins réels et éviter les formules recalculées inutilement', 'correct': True}, {'texte': 'Le fichier doit être supprimé et refait entièrement', 'correct': False}, {'texte': 'Excel ne peut pas gérer plus de 100 lignes', 'correct': False}, {'texte': 'Il faut changer d\'ordinateur uniquement', 'correct': False}], 'explication': "Des formules référençant des plages entières de colonnes ou des fonctions volatiles (comme AUJOURDHUI() ou ALEA()) recalculées à chaque modification ralentissent considérablement les gros fichiers — limiter les plages et optimiser les formules résout souvent le problème.", 'mots_cles': 'performance Excel, optimisation formules, diagnostic lenteur'},
    {'categorie': 'Microsoft PowerPoint', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Pourquoi limiter l'usage des transitions et animations complexes dans une présentation professionnelle ?", 'reponses': [{'texte': 'Elles peuvent distraire l\'audience du message principal et paraître peu professionnelles si excessives', 'correct': True}, {'texte': 'Elles sont toujours obligatoires', 'correct': False}, {'texte': 'Elles rendent le fichier plus petit', 'correct': False}, {'texte': 'Elles accélèrent la présentation', 'correct': False}], 'explication': "Un usage modéré et cohérent des animations soutient le message ; un usage excessif ou tape-à-l'œil détourne l'attention du contenu et peut nuire à la crédibilité professionnelle de la présentation.", 'mots_cles': 'sobriété animations, professionnalisme présentation'},
    {'categorie': 'Gestion des fichiers', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quel type de fichier est généralement associé à une présentation PowerPoint ?", 'reponses': [{'texte': '.pptx', 'correct': True}, {'texte': '.xlsx', 'correct': False}, {'texte': '.docx', 'correct': False}, {'texte': '.pdf uniquement', 'correct': False}], 'explication': "L'extension .pptx identifie un fichier de présentation PowerPoint moderne (basé sur XML), remplaçant l'ancien format .ppt.", 'mots_cles': 'extension pptx, PowerPoint, formats fichiers'},
    {'categorie': 'Raccourcis clavier', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Quel raccourci permet de dupliquer rapidement une diapositive dans PowerPoint ?", 'reponses': [{'texte': 'Ctrl + D', 'correct': True}, {'texte': 'Ctrl + C', 'correct': False}, {'texte': 'Ctrl + V', 'correct': False}, {'texte': 'Ctrl + X', 'correct': False}], 'explication': "Ctrl + D duplique la diapositive sélectionnée, un raccourci très pratique pour réutiliser une mise en page déjà prête.", 'mots_cles': 'dupliquer diapositive, PowerPoint, raccourci'},
]


class Command(BaseCommand):
    help = "Seed Batch 5 : 75 nouvelles questions (25 par module) — complète la banque à 300"

    def handle(self, *args, **options):
        from academie.management.commands._helper_seed_idempotent import creer_question_si_absente

        modules = {
            'INT': (QUESTIONS_INTERNET, 'Internet, Recherche et Productivité'),
            'IA': (QUESTIONS_IA, 'Intelligence Artificielle'),
            'BUR': (QUESTIONS_BUREAUTIQUE, 'Bureautique Professionnelle'),
        }

        total_creees = 0
        total_ignorees = 0

        for code, (questions, nom_module) in modules.items():
            module = ModuleBanque.objects.filter(code=code).first()
            if not module:
                self.stdout.write(self.style.ERROR(f"❌ Module {code} introuvable"))
                continue

            for q in questions:
                categorie = CategorieBanque.objects.filter(module=module, nom=q['categorie']).first()
                if not categorie:
                    self.stdout.write(self.style.WARNING(f"⚠️ Catégorie '{q['categorie']}' introuvable pour {code}"))
                    continue

                try:
                    cree = creer_question_si_absente(module, categorie, q)
                    if cree:
                        total_creees += 1
                    else:
                        total_ignorees += 1
                except Exception as e:
                    self.stdout.write(self.style.ERROR(f"❌ Erreur sur question '{q['enonce'][:50]}...' : {e}"))
                    continue

            self.stdout.write(self.style.SUCCESS(f"✅ {nom_module} : traité"))

        self.stdout.write(self.style.SUCCESS(
            f"\n🎉 BATCH 5 TERMINÉ : {total_creees} question(s) nouvellement créée(s), "
            f"{total_ignorees} déjà existante(s) ignorée(s) — 300/300 ATTEINT !"
        ))