# ================================================
# SEED_QUESTIONS_BATCH4.PY — Etape 4 (extension vers 300) — Sous-lot 1/2
# Usage : python manage.py seed_questions_batch4
# 75 questions (25 par module) — 225/300 après ce batch
# ================================================

from django.core.management.base import BaseCommand
from academie.models_banque import ModuleBanque, CategorieBanque, QuestionBanque


QUESTIONS_INTERNET = [
    {'categorie': 'Navigation Web', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quel symbole précède généralement l'adresse d'un site web sécurisé ?", 'reponses': [{'texte': 'https://', 'correct': True}, {'texte': 'ftp://', 'correct': False}, {'texte': 'www2://', 'correct': False}, {'texte': 'sec://', 'correct': False}], 'explication': "Le préfixe https:// (avec le S de « secure ») indique une connexion chiffrée, contrairement à http:// qui n'est pas sécurisé.", 'mots_cles': 'https, protocole, sécurité base'},
    {'categorie': 'Navigation Web', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Que se passe-t-il si vous fermez accidentellement un onglet important dans Chrome ?", 'reponses': [{'texte': 'Ctrl + Maj + T permet de le rouvrir immédiatement', 'correct': True}, {'texte': 'Il est perdu définitivement', 'correct': False}, {'texte': 'Il faut redémarrer l\'ordinateur', 'correct': False}, {'texte': 'Il faut réinstaller le navigateur', 'correct': False}], 'explication': "Ctrl+Maj+T rouvre le dernier onglet fermé (répétable plusieurs fois pour remonter dans l'historique de fermeture) — un raccourci qui évite bien des frustrations.", 'mots_cles': 'onglet fermé, raccourci récupération'},
    {'categorie': 'Navigation Web', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Quelle est la fonction d'un bloqueur de publicités (ad-blocker) ?", 'reponses': [{'texte': 'Empêcher l\'affichage de publicités et certains trackers publicitaires', 'correct': True}, {'texte': 'Bloquer tous les sites web', 'correct': False}, {'texte': 'Accélérer l\'ordinateur physiquement', 'correct': False}, {'texte': 'Supprimer les virus', 'correct': False}], 'explication': "Un bloqueur de publicités filtre les contenus publicitaires et certains scripts de suivi, améliorant souvent la vitesse de chargement et la confidentialité de navigation.", 'mots_cles': 'ad-blocker, publicité, confidentialité'},
    {'categorie': 'Recherche avancée', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Pourquoi est-il utile de reformuler sa recherche si les premiers résultats ne sont pas pertinents ?", 'reponses': [{'texte': 'Des mots-clés différents ou plus précis donnent souvent de meilleurs résultats', 'correct': True}, {'texte': 'Ça n\'a aucun effet', 'correct': False}, {'texte': 'Cela ralentit toujours la recherche', 'correct': False}, {'texte': 'Google refuse les recherches répétées', 'correct': False}], 'explication': "La formulation des mots-clés influence directement la pertinence des résultats — essayer des synonymes, être plus spécifique ou utiliser des opérateurs améliore souvent significativement les résultats.", 'mots_cles': 'reformulation, mots-clés, recherche efficace'},
    {'categorie': 'Recherche avancée', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Quelle recherche trouve des pages contenant « intelligence » MAIS PAS « artificielle » ?", 'reponses': [{'texte': 'intelligence -artificielle', 'correct': True}, {'texte': 'intelligence +artificielle', 'correct': False}, {'texte': 'intelligence AND artificielle', 'correct': False}, {'texte': 'intelligence=artificielle', 'correct': False}], 'explication': "Le signe moins (-) juste devant un mot, sans espace, exclut ce terme précis des résultats de recherche.", 'mots_cles': 'exclusion recherche, opérateur moins'},
    {'categorie': 'Opérateurs de recherche', 'niveau': 'professionnel', 'type': 'qcm', 'enonce': "Quelle combinaison trouve des offres d'emploi PDF publiées uniquement sur le site du gouvernement haïtien ?", 'reponses': [{'texte': 'site:gouv.ht filetype:pdf emploi', 'correct': True}, {'texte': 'gouv.ht emploi seulement', 'correct': False}, {'texte': 'emploi #gouv.ht', 'correct': False}, {'texte': 'site=gouv.ht pdf', 'correct': False}], 'explication': "Combiner plusieurs opérateurs (site: + filetype:) permet une recherche très précise et professionnelle, réduisant drastiquement le bruit dans les résultats.", 'mots_cles': 'opérateurs combinés, recherche experte'},
    {'categorie': 'Sécurité numérique', 'niveau': 'facile', 'type': 'vrai_faux', 'enonce': "Il est prudent de vérifier l'expéditeur exact d'un email avant de cliquer sur un lien qu'il contient.", 'reponses': [{'texte': 'Vrai', 'correct': True}, {'texte': 'Faux', 'correct': False}], 'explication': "Vérifier l'adresse email exacte de l'expéditeur (pas juste le nom affiché, qui peut être falsifié) permet de détecter de nombreuses tentatives de phishing.", 'mots_cles': 'vérification expéditeur, phishing, vigilance'},
    {'categorie': 'Sécurité numérique', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Quel est le rôle d'un gestionnaire de mots de passe ?", 'reponses': [{'texte': 'Stocker et générer des mots de passe uniques et complexes pour chaque service', 'correct': True}, {'texte': 'Accélérer la connexion Internet', 'correct': False}, {'texte': 'Supprimer les virus', 'correct': False}, {'texte': 'Bloquer les publicités', 'correct': False}], 'explication': "Un gestionnaire de mots de passe (comme Bitwarden, 1Password) génère et mémorise des mots de passe uniques et robustes pour chaque service, résolvant le problème de la réutilisation de mots de passe.", 'mots_cles': 'gestionnaire mots de passe, sécurité renforcée'},
    {'categorie': 'Sécurité numérique', 'niveau': 'professionnel', 'type': 'scenario_pro', 'enonce': "Un fichier joint « Facture_urgent.exe » arrive dans votre boîte professionnelle, prétendant venir d'un fournisseur habituel. Quel élément est le signal d'alerte le plus critique ?", 'reponses': [{'texte': 'L\'extension .exe pour un document censé être une facture — les factures sont normalement en PDF, jamais en exécutable', 'correct': True}, {'texte': 'Le mot « urgent » dans le nom', 'correct': False}, {'texte': 'La taille du fichier', 'correct': False}, {'texte': 'La couleur de l\'icône', 'correct': False}], 'explication': "Un fichier .exe (exécutable) déguisé en facture est un signal d'alerte majeur — les documents commerciaux légitimes sont en PDF/Word/Excel, jamais en exécutable, qui peut installer un logiciel malveillant.", 'mots_cles': 'fichier exécutable, malware, vigilance pièce jointe'},
    {'categorie': 'Google Workspace', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quelle application Google Workspace sert à créer des présentations (équivalent PowerPoint) ?", 'reponses': [{'texte': 'Google Slides', 'correct': True}, {'texte': 'Google Docs', 'correct': False}, {'texte': 'Google Sheets', 'correct': False}, {'texte': 'Google Keep', 'correct': False}], 'explication': "Google Slides est l'équivalent en ligne de PowerPoint — création de présentations collaboratives directement dans le navigateur.", 'mots_cles': 'Google Slides, présentation, Google Workspace'},
    {'categorie': 'Google Workspace', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Comment travailler sur un document Google Docs sans connexion Internet ?", 'reponses': [{'texte': 'Activer le mode hors connexion dans les paramètres Google Drive', 'correct': True}, {'texte': 'C\'est impossible sans Internet', 'correct': False}, {'texte': 'Télécharger et réinstaller Chrome', 'correct': False}, {'texte': 'Utiliser un autre navigateur', 'correct': False}], 'explication': "Google Drive propose un mode hors connexion qui synchronise automatiquement les modifications dès que la connexion Internet est rétablie, permettant de continuer à travailler sans interruption.", 'mots_cles': 'mode hors connexion, Google Drive, continuité travail'},
    {'categorie': 'Google Workspace', 'niveau': 'professionnel', 'type': 'scenario_pro', 'enonce': "Une équipe de 15 personnes doit accéder en LECTURE SEULE à un rapport financier sensible, sans pouvoir le modifier ni le télécharger. Quelle configuration Google Drive appliquer ?", 'reponses': [{'texte': 'Partager avec le rôle « Lecteur » et désactiver l\'option de téléchargement/impression/copie', 'correct': True}, {'texte': 'Partager avec le rôle « Éditeur » pour tous', 'correct': False}, {'texte': 'Envoyer le fichier par email à chacun', 'correct': False}, {'texte': 'Rendre le document public', 'correct': False}], 'explication': "Google Drive permet de combiner le rôle « Lecteur » avec des restrictions avancées (désactiver téléchargement/impression/copie) pour un contrôle fin sur des documents sensibles — essentiel en contexte financier confidentiel.", 'mots_cles': 'restrictions avancées, confidentialité, gestion accès'},
    {'categorie': 'Organisation des fichiers', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quelle extension identifie généralement une feuille de calcul Excel moderne ?", 'reponses': [{'texte': '.xlsx', 'correct': True}, {'texte': '.docx', 'correct': False}, {'texte': '.pptx', 'correct': False}, {'texte': '.mp3', 'correct': False}], 'explication': "L'extension .xlsx est le format moderne des fichiers Excel (basé sur XML), remplaçant l'ancien format .xls.", 'mots_cles': 'extension xlsx, Excel, formats fichiers'},
    {'categorie': 'Organisation des fichiers', 'niveau': 'professionnel', 'type': 'qcm', 'enonce': "Quelle convention de nommage de fichier facilite le mieux le tri chronologique automatique dans un dossier ?", 'reponses': [{'texte': 'AAAA-MM-JJ_NomDocument (ex: 2026-08-15_Rapport_Ventes)', 'correct': True}, {'texte': 'JJ-MM-AAAA_NomDocument', 'correct': False}, {'texte': 'NomDocument_JJMMAAAA', 'correct': False}, {'texte': 'Peu importe l\'ordre', 'correct': False}], 'explication': "Le format Année-Mois-Jour (ISO 8601) en préfixe garantit un tri alphabétique qui correspond automatiquement à un tri chronologique — une convention professionnelle largement recommandée.", 'mots_cles': 'convention nommage, tri chronologique, ISO 8601'},
    {'categorie': 'Collaboration', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quel outil permet une réunion vidéo en ligne avec partage d'écran ?", 'reponses': [{'texte': 'Google Meet ou Zoom', 'correct': True}, {'texte': 'Google Docs', 'correct': False}, {'texte': 'Google Sheets', 'correct': False}, {'texte': 'Gmail', 'correct': False}], 'explication': "Google Meet et Zoom sont des outils de visioconférence permettant réunions vidéo, partage d'écran et enregistrement — essentiels pour le travail à distance moderne.", 'mots_cles': 'visioconférence, Google Meet, Zoom'},
    {'categorie': 'Collaboration', 'niveau': 'professionnel', 'type': 'etude_cas', 'enonce': "Une équipe répartie sur 3 fuseaux horaires (Haïti, France, Sénégal) peine à organiser des réunions synchrones efficaces. Quelle approche hybride recommandez-vous ?", 'reponses': [{'texte': 'Limiter les réunions synchrones à l\'essentiel, privilégier la communication asynchrone (documents partagés, messages enregistrés) pour le reste', 'correct': True}, {'texte': 'Forcer tout le monde à travailler sur l\'horaire de Haïti', 'correct': False}, {'texte': 'Ne jamais organiser de réunion', 'correct': False}, {'texte': 'Communiquer uniquement par téléphone', 'correct': False}], 'explication': "Face à des fuseaux horaires multiples, la meilleure pratique moderne combine des réunions synchrones ciblées et rares avec une communication asynchrone riche (documents commentés, vidéos courtes) — respectant le rythme de chacun.", 'mots_cles': 'travail asynchrone, fuseaux horaires, collaboration distribuée'},
    {'categorie': 'Productivité', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quel est l'avantage d'utiliser un agenda numérique partagé plutôt qu'un agenda papier en équipe ?", 'reponses': [{'texte': 'Visibilité en temps réel des disponibilités de chacun et rappels automatiques', 'correct': True}, {'texte': 'Il n\'y a aucun avantage', 'correct': False}, {'texte': 'C\'est plus lent à consulter', 'correct': False}, {'texte': 'Cela coûte toujours plus cher', 'correct': False}], 'explication': "Un agenda numérique partagé (Google Calendar) offre une visibilité instantanée des disponibilités de l'équipe et des rappels automatiques, éliminant les conflits d'organisation fréquents avec un agenda papier individuel.", 'mots_cles': 'agenda partagé, planification équipe, productivité'},
    {'categorie': 'Productivité', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Quelle technique de gestion du temps consiste à travailler par intervalles de 25 minutes suivis d'une courte pause ?", 'reponses': [{'texte': 'La technique Pomodoro', 'correct': True}, {'texte': 'La matrice Eisenhower', 'correct': False}, {'texte': 'Le time blocking', 'correct': False}, {'texte': 'Le GTD (Getting Things Done)', 'correct': False}], 'explication': "La technique Pomodoro alterne des sessions de travail concentré (généralement 25 min) et de courtes pauses, aidant à maintenir la concentration et à réduire la fatigue mentale.", 'mots_cles': 'Pomodoro, gestion du temps, concentration'},
    {'categorie': 'Navigation Web', 'niveau': 'professionnel', 'type': 'etude_cas', 'enonce': "Un site e-commerce affiche des prix incohérents selon le navigateur utilisé pour le consulter. Quelle est l'explication technique la plus probable ?", 'reponses': [{'texte': 'Le site utilise possiblement des cookies pour personnaliser les prix selon l\'historique de navigation (tracking commercial)', 'correct': True}, {'texte': 'C\'est toujours un bug du site', 'correct': False}, {'texte': 'Les navigateurs affichent des devises différentes', 'correct': False}, {'texte': 'C\'est impossible techniquement', 'correct': False}], 'explication': "Certains sites utilisent des cookies de tracking pour ajuster dynamiquement les prix selon le comportement présumé de l'utilisateur (historique, appareil) — une pratique controversée à connaître pour un usage numérique averti.", 'mots_cles': 'tracking commercial, cookies, prix dynamiques'},
    {'categorie': 'Recherche avancée', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Que permet l'onglet « Images » de Google lors d'une recherche par image inversée ?", 'reponses': [{'texte': 'Retrouver l\'origine ou des occurrences similaires d\'une image donnée', 'correct': True}, {'texte': 'Modifier l\'image automatiquement', 'correct': False}, {'texte': 'Supprimer l\'image du web', 'correct': False}, {'texte': 'Compresser l\'image', 'correct': False}], 'explication': "La recherche par image inversée permet de retrouver la source d'une image, vérifier son authenticité, ou trouver des versions similaires — un outil précieux pour vérifier l'authenticité d'un visuel.", 'mots_cles': 'recherche image inversée, vérification visuelle'},
    {'categorie': 'Productivité', 'niveau': 'professionnel', 'type': 'qcm', 'enonce': "Pourquoi le « time blocking » (blocage de créneaux dédiés dans l'agenda) améliore-t-il la productivité ?", 'reponses': [{'texte': 'Il protège des plages de temps dédiées à des tâches spécifiques, réduisant les interruptions et le multitâche', 'correct': True}, {'texte': 'Il n\'a aucun effet réel', 'correct': False}, {'texte': 'Il augmente le nombre de réunions', 'correct': False}, {'texte': 'Il fonctionne uniquement pour les tâches courtes', 'correct': False}], 'explication': "Le time blocking réserve des créneaux spécifiques pour des tâches précises, créant une barrière contre les interruptions et le multitâche, deux facteurs majeurs de perte de productivité.", 'mots_cles': 'time blocking, agenda, concentration profonde'},
    {'categorie': 'Sécurité numérique', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Que signifie l'acronyme « CAPTCHA » couramment rencontré sur les formulaires web ?", 'reponses': [{'texte': 'Un test permettant de distinguer un humain d\'un robot automatisé', 'correct': True}, {'texte': 'Un type de virus', 'correct': False}, {'texte': 'Un protocole de connexion', 'correct': False}, {'texte': 'Un format de fichier', 'correct': False}], 'explication': "Le CAPTCHA (Completely Automated Public Turing test to tell Computers and Humans Apart) protège les formulaires contre les soumissions automatisées malveillantes (spam, création massive de faux comptes).", 'mots_cles': 'CAPTCHA, protection formulaire, anti-bot'},
    {'categorie': 'Collaboration', 'niveau': 'intermediaire', 'type': 'vrai_faux', 'enonce': "Dans un outil de gestion de projet en ligne (type Trello, Asana), chaque tâche peut généralement être assignée à un responsable précis.", 'reponses': [{'texte': 'Vrai', 'correct': True}, {'texte': 'Faux', 'correct': False}], 'explication': "Les outils de gestion de projet permettent d'assigner clairement chaque tâche à un ou plusieurs responsables, avec des dates d'échéance — une fonctionnalité clé pour la clarté organisationnelle en équipe.", 'mots_cles': 'gestion de projet, assignation tâches, responsabilité'},
    {'categorie': 'Google Workspace', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Dans Google Sheets, quelle fonction permet d'importer automatiquement des données depuis une autre feuille de calcul ?", 'reponses': [{'texte': 'IMPORTRANGE', 'correct': True}, {'texte': 'RECHERCHEV', 'correct': False}, {'texte': 'CONCATENER', 'correct': False}, {'texte': 'SOMME', 'correct': False}], 'explication': "IMPORTRANGE() permet de récupérer des données d'une autre feuille Google Sheets, très utile pour centraliser des données provenant de plusieurs sources tout en gardant une seule source de vérité.", 'mots_cles': 'IMPORTRANGE, Google Sheets avancé, centralisation données'},
    {'categorie': 'Sécurité numérique', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Que faire régulièrement pour protéger ses appareils contre les failles de sécurité connues ?", 'reponses': [{'texte': 'Effectuer les mises à jour logicielles régulièrement', 'correct': True}, {'texte': 'Ne jamais mettre à jour ses logiciels', 'correct': False}, {'texte': 'Désactiver l\'antivirus', 'correct': False}, {'texte': 'Partager son mot de passe avec des amis', 'correct': False}], 'explication': "Les mises à jour logicielles corrigent souvent des failles de sécurité découvertes — les reporter indéfiniment expose l'appareil à des vulnérabilités connues et exploitables.", 'mots_cles': 'mises à jour, failles de sécurité, maintenance'},
]

QUESTIONS_IA = [
    {'categorie': 'Fondamentaux', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quel domaine de l'IA permet à un ordinateur de « comprendre » et générer du langage humain ?", 'reponses': [{'texte': 'Le traitement du langage naturel (NLP)', 'correct': True}, {'texte': 'La vision par ordinateur', 'correct': False}, {'texte': 'La robotique', 'correct': False}, {'texte': 'La cryptographie', 'correct': False}], 'explication': "Le NLP (Natural Language Processing / Traitement du Langage Naturel) est la branche de l'IA dédiée à la compréhension et génération du texte et de la parole humaine — fondement des chatbots comme ChatGPT.", 'mots_cles': 'NLP, traitement langage naturel, fondamentaux'},
    {'categorie': 'Fondamentaux', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Quel domaine de l'IA permet de reconnaître des objets dans une photo ?", 'reponses': [{'texte': 'La vision par ordinateur (Computer Vision)', 'correct': True}, {'texte': 'Le NLP', 'correct': False}, {'texte': 'Le clustering', 'correct': False}, {'texte': 'La blockchain', 'correct': False}], 'explication': "La vision par ordinateur permet aux systèmes IA d'analyser et interpréter des images/vidéos — utilisée notamment dans la reconnaissance faciale, les voitures autonomes et le tri automatique d'images.", 'mots_cles': 'vision par ordinateur, reconnaissance image'},
    {'categorie': 'IA générative', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Que signifie le terme « multimodal » appliqué à une IA générative récente ?", 'reponses': [{'texte': 'Capable de traiter et générer plusieurs types de contenus (texte, image, audio) simultanément', 'correct': True}, {'texte': 'Fonctionne uniquement sur plusieurs appareils', 'correct': False}, {'texte': 'Nécessite plusieurs comptes utilisateur', 'correct': False}, {'texte': 'Un type de virus informatique', 'correct': False}], 'explication': "Une IA multimodale (comme les versions récentes de GPT, Gemini) peut traiter simultanément texte, image, audio et parfois vidéo dans une même conversation, offrant des capacités bien plus riches qu'une IA mono-format.", 'mots_cles': 'IA multimodale, capacités avancées'},
    {'categorie': 'Prompt Engineering', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Pourquoi indiquer une longueur maximale (« en 100 mots ») dans un prompt peut-il être utile professionnellement ?", 'reponses': [{'texte': 'Garantit une réponse concise et directement utilisable sans besoin de réécriture ou de coupe manuelle', 'correct': True}, {'texte': 'Cela n\'a aucun effet sur la réponse', 'correct': False}, {'texte': 'Cela empêche l\'IA de répondre correctement', 'correct': False}, {'texte': 'C\'est toujours ignoré par l\'IA', 'correct': False}], 'explication': "Préciser une contrainte de longueur aide l'IA à calibrer sa réponse au format attendu (résumé exécutif, post réseau social, email court), évitant un travail supplémentaire de synthèse ou de coupe.", 'mots_cles': 'contrainte longueur, prompt précis, efficacité'},
    {'categorie': 'Prompt Engineering', 'niveau': 'professionnel', 'type': 'analyse_prompt_ia', 'enonce': "Un prompt indique : « Réponds toujours en respectant ce format : Titre / Résumé / 3 points clés / Conclusion ». Quel avantage professionnel majeur apporte cette structuration systématique ?", 'reponses': [{'texte': 'Cohérence et prévisibilité des réponses, facilitant leur intégration directe dans des rapports ou processus automatisés', 'correct': True}, {'texte': 'Aucun avantage particulier', 'correct': False}, {'texte': 'Cela ralentit systématiquement l\'IA', 'correct': False}, {'texte': 'Cela empêche toute créativité', 'correct': False}], 'explication': "Un format de réponse systématique et prévisible facilite grandement l'intégration des réponses IA dans des workflows professionnels (rapports standardisés, automatisations, templates), un principe clé du prompt engineering avancé.", 'mots_cles': 'structuration reponse, workflow professionnel, prompt avance'},
    {'categorie': 'Éthique', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Pourquoi certaines entreprises publient-elles une « charte d'usage de l'IA » pour leurs employés ?", 'reponses': [{'texte': 'Pour encadrer un usage responsable, protéger les données confidentielles et clarifier les limites acceptables', 'correct': True}, {'texte': 'Pour interdire totalement l\'usage de tout outil numérique', 'correct': False}, {'texte': 'C\'est une obligation légale universelle sans exception', 'correct': False}, {'texte': 'Cela n\'a aucune utilité pratique', 'correct': False}], 'explication': "Une charte d'usage de l'IA en entreprise établit des règles claires (quelles données peuvent être partagées, quels outils sont approuvés, comment déclarer l'usage) pour un usage éthique, sécurisé et cohérent au sein de l'organisation.", 'mots_cles': 'charte usage IA, gouvernance entreprise, cadre éthique'},
    {'categorie': 'Éthique', 'niveau': 'avance', 'type': 'scenario_pro', 'enonce': "Une IA générative propose une image de personne réaliste pour illustrer un article, alors qu'aucune vraie photo n'était disponible. Quelle précaution éditoriale est recommandée ?", 'reponses': [{'texte': 'Mentionner clairement que l\'image est générée par IA pour éviter toute confusion avec une vraie photographie', 'correct': True}, {'texte': 'Publier sans aucune mention', 'correct': False}, {'texte': 'Prétendre que c\'est une vraie photo', 'correct': False}, {'texte': 'Ne jamais utiliser d\'images générées', 'correct': False}], 'explication': "La transparence sur l'origine synthétique d'une image (mention « image générée par IA ») est une pratique éthique croissante, évitant de tromper le public sur l'authenticité du contenu visuel.", 'mots_cles': 'transparence image IA, éthique éditoriale'},
    {'categorie': 'Vérification des réponses', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Une IA affirme qu'une loi haïtienne précise existe avec un numéro d'article exact. Quelle vérification est indispensable avant de citer cette information ?", 'reponses': [{'texte': 'Consulter directement le texte légal officiel (Moniteur, ministère concerné) pour confirmer son existence et son contenu exact', 'correct': True}, {'texte': 'Faire confiance car le numéro d\'article semble précis', 'correct': False}, {'texte': 'Demander confirmation à la même IA', 'correct': False}, {'texte': 'Ignorer la vérification, ce n\'est pas grave', 'correct': False}], 'explication': "Les IA peuvent halluciner des références légales très précises mais inexistantes ou incorrectes. Pour toute information juridique, la source officielle primaire reste la seule vérification fiable — un point critique en contexte professionnel.", 'mots_cles': 'vérification juridique, hallucination précise, rigueur légale'},
    {'categorie': 'Cas professionnels', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Comment l'IA peut-elle assister un commerçant dans la gestion de son inventaire ?", 'reponses': [{'texte': 'En analysant les tendances de vente pour prédire les besoins de réapprovisionnement', 'correct': True}, {'texte': 'En livrant physiquement les produits', 'correct': False}, {'texte': 'En remplaçant totalement la gestion humaine', 'correct': False}, {'texte': 'Elle ne peut pas aider dans ce domaine', 'correct': False}], 'explication': "Les outils d'IA analytique peuvent identifier des tendances de vente et prédire les besoins futurs de stock, aidant à optimiser les commandes et réduire les ruptures ou surstocks — une application concrète pour la gestion de stock.", 'mots_cles': 'IA gestion stock, prédiction ventes, cas d\'usage'},
    {'categorie': 'Automatisation', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Quel est le principal bénéfice d'automatiser le tri des emails entrants par catégorie (facture, support, spam) ?", 'reponses': [{'texte': 'Traitement plus rapide et priorisation efficace sans effort manuel répétitif', 'correct': True}, {'texte': 'Cela supprime tous les emails automatiquement', 'correct': False}, {'texte': 'Cela ralentit la réception des emails', 'correct': False}, {'texte': 'Aucun bénéfice mesurable', 'correct': False}], 'explication': "L'automatisation du tri d'emails par catégorie réduit le temps de traitement manuel et assure qu'aucun message important ne soit noyé dans le flux quotidien — un gain de productivité mesurable.", 'mots_cles': 'tri automatique email, productivité, automatisation'},
    {'categorie': 'Fondamentaux', 'niveau': 'facile', 'type': 'vrai_faux', 'enonce': "L'intelligence artificielle est un concept apparu uniquement dans les années 2020 avec ChatGPT.", 'reponses': [{'texte': 'Vrai', 'correct': False}, {'texte': 'Faux', 'correct': True}], 'explication': "C'est faux : le concept d'IA existe depuis les années 1950 (Alan Turing, Dartmouth Conference 1956). Ce qui a changé récemment est la puissance de calcul et le volume de données disponibles, rendant les IA génératives grand public accessibles.", 'mots_cles': 'histoire IA, fondamentaux, contexte'},
    {'categorie': 'IA générative', 'niveau': 'professionnel', 'type': 'qcm', 'enonce': "Pourquoi certaines entreprises préfèrent-elles héberger leur propre modèle IA plutôt que d'utiliser une API externe (ChatGPT, Gemini) pour des données sensibles ?", 'reponses': [{'texte': 'Pour garder un contrôle total sur la confidentialité des données, sans les transmettre à un tiers externe', 'correct': True}, {'texte': 'C\'est toujours moins cher', 'correct': False}, {'texte': 'C\'est plus simple à mettre en place', 'correct': False}, {'texte': 'Cela n\'a aucun rapport avec la confidentialité', 'correct': False}], 'explication': "L'hébergement d'un modèle IA en interne (on-premise ou cloud privé) permet de garder un contrôle total sur des données sensibles sans les transmettre à un fournisseur tiers — un choix stratégique pour certains secteurs réglementés (santé, finance, défense).", 'mots_cles': 'IA hébergée, confidentialité données, choix stratégique'},
    {'categorie': 'Cas professionnels', 'niveau': 'professionnel', 'type': 'scenario_pro', 'enonce': "Un cabinet comptable utilise l'IA pour pré-remplir des déclarations fiscales de clients. Quelle vérification reste absolument non-négociable avant soumission officielle ?", 'reponses': [{'texte': 'Validation complète par un comptable qualifié avant toute soumission officielle aux autorités fiscales', 'correct': True}, {'texte': 'Aucune vérification n\'est nécessaire', 'correct': False}, {'texte': 'Vérifier uniquement l\'orthographe', 'correct': False}, {'texte': 'Faire confiance totalement à l\'IA pour ce type de tâche', 'correct': False}], 'explication': "Les déclarations fiscales ont des conséquences légales et financières réelles — l'IA peut accélérer la préparation mais la validation finale par un professionnel qualifié reste absolument indispensable avant toute soumission officielle.", 'mots_cles': 'validation humaine obligatoire, conséquences légales, IA fiscale'},
    {'categorie': 'Vérification des réponses', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Que signifie concrètement « croiser les sources » lors de la vérification d'une information donnée par une IA ?", 'reponses': [{'texte': 'Chercher la même information sur au moins 2 sources indépendantes et fiables avant de la considérer comme vraie', 'correct': True}, {'texte': 'Poser la même question à l\'IA deux fois', 'correct': False}, {'texte': 'Demander l\'avis d\'un ami', 'correct': False}, {'texte': 'Copier l\'information telle quelle', 'correct': False}], 'explication': "Croiser les sources signifie vérifier une information auprès de plusieurs origines indépendantes (pas la même IA deux fois, ni des sources liées entre elles) — une pratique fondamentale de vérification de l'information.", 'mots_cles': 'croisement sources, vérification indépendante, méthodologie'},
]

QUESTIONS_BUREAUTIQUE = [
    {'categorie': 'Microsoft Word', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quel raccourci clavier annule la dernière action effectuée dans Word ?", 'reponses': [{'texte': 'Ctrl + Z', 'correct': True}, {'texte': 'Ctrl + Y', 'correct': False}, {'texte': 'Ctrl + X', 'correct': False}, {'texte': 'Ctrl + A', 'correct': False}], 'explication': "Ctrl+Z (Undo) annule la dernière action, un raccourci de secours essentiel utilisable dans presque tous les logiciels.", 'mots_cles': 'Ctrl+Z, annuler, raccourci essentiel'},
    {'categorie': 'Microsoft Word', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Comment insérer un tableau de 3 colonnes et 4 lignes dans Word ?", 'reponses': [{'texte': 'Insertion > Tableau > sélectionner 3x4', 'correct': True}, {'texte': 'Taper directement le tableau avec des tabulations', 'correct': False}, {'texte': 'Insertion > Image', 'correct': False}, {'texte': 'Ce n\'est pas possible dans Word', 'correct': False}], 'explication': "L'onglet Insertion > Tableau permet de créer rapidement une grille aux dimensions choisies, avec toutes les fonctionnalités de mise en forme de tableau natives.", 'mots_cles': 'insertion tableau, Word intermédiaire'},
    {'categorie': 'Microsoft Excel', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quelle fonction Excel trouve la valeur la plus élevée dans une plage de cellules ?", 'reponses': [{'texte': '=MAX(plage)', 'correct': True}, {'texte': '=GRAND(plage)', 'correct': False}, {'texte': '=HAUT(plage)', 'correct': False}, {'texte': '=TOP(plage)', 'correct': False}], 'explication': "=MAX() retourne la valeur la plus élevée d'une plage — son opposée =MIN() retourne la valeur la plus basse. Deux fonctions statistiques de base très utilisées.", 'mots_cles': 'MAX, Excel de base, fonctions statistiques'},
    {'categorie': 'Microsoft Excel', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "À quoi sert la mise en forme conditionnelle dans Excel ?", 'reponses': [{'texte': 'Changer automatiquement l\'apparence d\'une cellule selon une condition (ex: rouge si négatif)', 'correct': True}, {'texte': 'Verrouiller définitivement une cellule', 'correct': False}, {'texte': 'Supprimer les doublons', 'correct': False}, {'texte': 'Trier les données alphabétiquement', 'correct': False}], 'explication': "La mise en forme conditionnelle applique automatiquement un style visuel (couleur, icône) selon des règles définies, rendant les données anormales ou importantes immédiatement visibles sans lecture attentive de chaque cellule.", 'mots_cles': 'mise en forme conditionnelle, visualisation données'},
    {'categorie': 'Microsoft Excel', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Quelle fonction combine du texte de plusieurs cellules en une seule (ex: prénom + nom) ?", 'reponses': [{'texte': 'CONCATENER() ou l\'opérateur &', 'correct': True}, {'texte': 'SOMME()', 'correct': False}, {'texte': 'DIVISER()', 'correct': False}, {'texte': 'SEPARER()', 'correct': False}], 'explication': "CONCATENER() (ou plus simplement l'opérateur &) fusionne le contenu de plusieurs cellules texte en une seule chaîne — très utile pour créer des noms complets, des adresses ou des identifiants combinés.", 'mots_cles': 'CONCATENER, fusion texte, Excel avancé'},
    {'categorie': 'Microsoft Excel', 'niveau': 'professionnel', 'type': 'analyse_excel', 'enonce': "Une formule RECHERCHEV renvoie systématiquement #N/A alors que la valeur cherchée semble présente dans le tableau. Quelle cause technique fréquente devez-vous vérifier en premier ?", 'reponses': [{'texte': 'Un espace invisible ou une différence de format (texte vs nombre) entre la valeur cherchée et celle du tableau', 'correct': True}, {'texte': 'Excel est corrompu', 'correct': False}, {'texte': 'Il faut redémarrer l\'ordinateur', 'correct': False}, {'texte': 'La formule RECHERCHEV n\'existe plus', 'correct': False}], 'explication': "L'erreur #N/A sur une RECHERCHEV apparemment correcte vient très souvent d'une différence subtile invisible à l'œil nu : espace superflu, ou une valeur stockée en texte alors qu'elle est cherchée en tant que nombre (ou inversement).", 'mots_cles': 'erreur #N/A, diagnostic RECHERCHEV, format donnees'},
    {'categorie': 'Microsoft PowerPoint', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Comment ajouter des notes du présentateur visibles uniquement par lui pendant la présentation ?", 'reponses': [{'texte': 'Via l\'onglet Affichage > Notes, des notes peuvent être ajoutées pour chaque diapositive et ne sont visibles que pour le présentateur', 'correct': True}, {'texte': 'Impossible, c\'est une fonctionnalité absente de PowerPoint', 'correct': False}, {'texte': 'En modifiant le fichier dans un éditeur de texte', 'correct': False}, {'texte': 'Par le menu Outils > Options', 'correct': False}], 'explication': "L'onglet Affichage > Notes permet d'ajouter des commentaires privés pour chaque diapositive, visibles uniquement en mode présentateur (et non sur l'écran projeté)."},
    {'categorie': 'Microsoft PowerPoint', 'niveau': 'facile', 'type': 'qcm', 'enonce': "Quel raccourci permet de lancer un diaporama depuis la diapositive courante ?", 'reponses': [{'texte': 'Maj + F5', 'correct': True}, {'texte': 'F5', 'correct': False}, {'texte': 'Ctrl + F5', 'correct': False}, {'texte': 'Alt + F5', 'correct': False}], 'explication': "Maj+F5 lance le diaporama depuis la diapositive actuellement sélectionnée, utile pour tester une section précise sans repartir du début.", 'mots_cles': 'PowerPoint, raccourci, diaporama'},
    {'categorie': 'Microsoft PowerPoint', 'niveau': 'avance', 'type': 'qcm', 'enonce': "Quel outil permet de créer un sommaire automatique des diapositives dans PowerPoint ?", 'reponses': [{'texte': 'Le mode Plan (Affichage > Plan) permet de générer un sommaire structuré', 'correct': True}, {'texte': 'Il n\'existe pas de sommaire automatique dans PowerPoint', 'correct': False}, {'texte': 'Il faut utiliser Word pour cela', 'correct': False}, {'texte': 'Le sommaire se génère en imprimant le diaporama', 'correct': False}], 'explication': "Le mode Plan (Affichage > Plan) permet de visualiser et organiser la structure de la présentation sous forme de titres, et d'en générer un sommaire.", 'mots_cles': 'PowerPoint, sommaire, plan'},
    {'categorie': 'Gestion des fichiers', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Quel est le principal avantage d'utiliser un service de stockage cloud (Google Drive, OneDrive) par rapport à un disque dur externe ?", 'reponses': [{'texte': 'Accessibilité depuis n\'importe quel appareil connecté et sauvegarde automatique', 'correct': True}, {'texte': 'C\'est toujours plus rapide qu\'un disque dur', 'correct': False}, {'texte': 'Cela ne nécessite pas de connexion Internet', 'correct': False}, {'texte': 'Les fichiers sont toujours plus petits', 'correct': False}], 'explication': "Le stockage cloud permet un accès universel à ses fichiers depuis tout appareil connecté, avec des sauvegardes automatiques, sans risque de perte physique.", 'mots_cles': 'cloud, stockage en ligne, accessibilité'},
    {'categorie': 'Gestion des fichiers', 'niveau': 'professionnel', 'type': 'qcm', 'enonce': "Quelle pratique permet de retrouver un fichier perdu dans un dossier contenant des centaines de documents ?", 'reponses': [{'texte': 'Utiliser la barre de recherche du système d\'exploitation (Windows Search, Spotlight) avec des mots-clés', 'correct': True}, {'texte': 'Trier les fichiers par date de modification et parcourir la liste', 'correct': False}, {'texte': 'Ouvrir chaque fichier un par un', 'correct': False}, {'texte': 'Supprimer le dossier et recommencer', 'correct': False}], 'explication': "Les outils de recherche intégrés (Spotlight sur Mac, recherche Windows) sont très puissants pour retrouver rapidement un fichier par son nom, son type ou son contenu.", 'mots_cles': 'recherche fichiers, Windows Search, Spotlight'},
    {'categorie': 'Productivité', 'niveau': 'intermediaire', 'type': 'qcm', 'enonce': "Quel est l'avantage d'organiser ses fichiers par projet plutôt que par type (ex: tous les PDF ensemble) ?", 'reponses': [{'texte': 'Regrouper tous les documents relatifs à un projet facilite la navigation et le contexte', 'correct': True}, {'texte': 'Cela n\'a pas d\'importance', 'correct': False}, {'texte': 'Cela ralentit la recherche', 'correct': False}, {'texte': 'C\'est recommandé uniquement pour les photos', 'correct': False}], 'explication': "Organiser par projet permet de retrouver facilement tous les documents liés à un même projet (rapports, images, notes) en un seul endroit, sans multiplier les allers-retours.", 'mots_cles': 'organisation par projet, productivité'},
]


class Command(BaseCommand):
    help = "Seed Batch 4 : 75 nouvelles questions (25 par module) — extension vers 300"

    def handle(self, *args, **options):
        from academie.management.commands._helper_seed_idempotent import creer_question_si_absente

        modules = {
            'INT': (QUESTIONS_INTERNET, 'Internet, Recherche et Productivité'),
            'IA': (QUESTIONS_IA, 'Intelligence Artificielle'),
            'BUR': (QUESTIONS_BUREAUTIQUE, 'Bureautique Professionnelle'),
        }

        total_creees = 0
        total_ignorees = 0

        for code, (questions, nom_module) in modules.items():
            module = ModuleBanque.objects.filter(code=code).first()
            if not module:
                self.stdout.write(self.style.ERROR(f"❌ Module {code} introuvable"))
                continue

            for q in questions:
                categorie = CategorieBanque.objects.filter(module=module, nom=q['categorie']).first()
                if not categorie:
                    self.stdout.write(self.style.WARNING(f"⚠️ Catégorie '{q['categorie']}' introuvable pour {code}"))
                    continue

                try:
                    cree = creer_question_si_absente(module, categorie, q)
                    if cree:
                        total_creees += 1
                    else:
                        total_ignorees += 1
                except Exception as e:
                    self.stdout.write(self.style.ERROR(f"❌ Erreur sur question '{q['enonce'][:50]}...' : {e}"))
                    continue

            self.stdout.write(self.style.SUCCESS(f"✅ {nom_module} : traité"))

        self.stdout.write(self.style.SUCCESS(
            f"\n🎉 BATCH 4 TERMINÉ : {total_creees} question(s) nouvellement créée(s), "
            f"{total_ignorees} déjà existante(s) ignorée(s) (aucun doublon)"
        ))