"""
Django settings for blessy_tech_academy project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The SECRET_KEY must be provided via environment variables in production.
# Do NOT commit a .env file containing real secrets to version control.
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Email backend pour les tests en développement (affiche les emails dans le terminal)
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='*',
    cast=lambda v: [s.strip() for s in v.split(',')]
)
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]
)
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_ckeditor_5',
    'adminsortable2',   # ← AJOUTE ICI
    'simple_history',   # ← AJOUTE ICI
    'rest_framework',
    'rest_framework.authtoken',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'academie',
    
]
# Debug Toolbar (développement uniquement)
if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'academie.middleware.SecurityHeadersMiddleware',   # ← Security Headers
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',  # ← AJOUTE ICI

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
MIDDLEWARE += ['academie.middleware.MonitoringPerformanceMiddleware']
# SETTINGS.PY — Ajout middleware Academie courante
MIDDLEWARE += ['academie.middleware.AcademieCouranteMiddleware']

# Debug Toolbar (développement uniquement)
if DEBUG:
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
    INTERNAL_IPS = ['127.0.0.1']

ROOT_URLCONF = 'blessy_tech_academy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'academie.context_processors.notifications_non_lues',
                'academie.context_processors.academie_courante',   # ← AJOUTER ICI

            ],
        },
    },
]

WSGI_APPLICATION = 'blessy_tech_academy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config(
            'DATABASE_URL',
            default='sqlite:///db.sqlite3'
        ),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

LANGUAGES = [
    ('fr', 'Français'),
    ('ht', 'Kreyòl'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

if DEBUG:
    # En développement : Django sert directement les fichiers statiques
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    # En production : WhiteNoise sert les fichiers (optimisés et compressés)
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ================================================
# CKEditor 5 Configuration
# ================================================

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'fontSize', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', '|',
            'bulletedList', 'numberedList', '|',
            'link', 'insertImage', 'mediaEmbed', '|',
            'blockQuote', 'insertTable', 'codeBlock', '|',
            'undo', 'redo'
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative',
                'imageStyle:inline',
                'imageStyle:block',
                'imageStyle:side',
                'imageStyle:wrapText',
                'imageStyle:breakText',
            ],
        },
        'table': {
            'contentToolbar': [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableProperties',
                'tableCellProperties',
            ]
        },
        'height': 400,
        'width': '100%',
        'language': 'fr',
    },
    'minimal': {
        'toolbar': [
            'bold', 'italic', 'underline', '|',
            'bulletedList', 'numberedList', '|',
            'link', '|',
            'undo', 'redo'
        ],
        'height': 200,
        'width': '100%',
        'language': 'fr',
    }
}

# Dossier pour les images uploadées via CKEditor
CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Logging des erreurs en production (sans DEBUG=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'errors.log',
        },
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}


# Sites framework (requis par allauth)
SITE_ID = 1

# Allauth configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True


# ========== Sécurité des cookies ==========
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# ========== HSTS et HTTPS ==========
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ========== Protection XSS ==========
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

# ========== Anti-clickjacking ==========
X_FRAME_OPTIONS = 'DENY'

# ========== Content Security Policy ==========
# Note: Le CSP principal est géré par SecurityHeadersMiddleware
# Ces variables sont utilisées comme fallback par Django
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    "https://cdn.ckeditor.com",
    "https://cdn.jsdelivr.net",
    "https://www.googletagmanager.com",
    "https://www.google-analytics.com",
)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",
    "https://cdn.ckeditor.com",
    "https://cdn.jsdelivr.net",
    "https://fonts.googleapis.com",
)
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_FONT_SRC = ("'self'", "https://cdn.ckeditor.com", "https://fonts.gstatic.com")
CSP_CONNECT_SRC = ("'self'", "https://www.google-analytics.com")
CSP_MANIFEST_SRC = ("'self'",)
CSP_FRAME_ANCESTORS = ("'self'",)
CSP_BASE_URI = ("'self'",)
CSP_FORM_ACTION = ("'self'",)
CSP_FRAME_SRC = ("'self'",)
CSP_OBJECT_SRC = ("'none'",)

if DEBUG:
    # En développement, on assouplit pour permettre localhost
    CSP_DEFAULT_SRC = ("'self'", "http://127.0.0.1:8000", "http://localhost:8000")
    CSP_CONNECT_SRC = ("'self'", "http://127.0.0.1:8000", "http://localhost:8000", "https://www.google-analytics.com")
else:
    # En production, on renforce la sécurité
    CSP_UPGRADE_INSECURE_REQUESTS = True

    # ================================================
# SETTINGS.PY — Configuration Email BTA
# (Ajoute ce bloc à la fin de settings.py)
# ================================================

SITE_URL = config('SITE_URL', default='https://blessy-tech-academy-production.up.railway.app')

# --- Adresses professionnelles dédiées ---
EMAIL_CONTACT = 'contact@blessytechacademy.com'
EMAIL_SUPPORT = 'support@blessytechacademy.com'
EMAIL_ADMISSIONS = 'admissions@blessytechacademy.com'
EMAIL_CERTIFICATS = 'certificats@blessytechacademy.com'
EMAIL_FORMATIONS = 'formations@blessytechacademy.com'
EMAIL_RECRUTEMENT = 'recrutement@blessytechacademy.com'
EMAIL_NEWSLETTER = 'newsletter@blessytechacademy.com'
EMAIL_NOREPLY = 'noreply@blessytechacademy.com'

DEFAULT_FROM_EMAIL = EMAIL_NOREPLY

# --- Backend SMTP (aujourd'hui) — bascule vers un provider en changeant UNIQUEMENT ici ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')       # ou smtp-relay.brevo.com, smtp.mailgun.org...
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)

# En développement, afficher les emails dans le terminal
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# ========== Journalisation sécurité ==========
LOGGING['loggers']['django.security'] = {
    'handlers': ['file', 'console'],
    'level': 'WARNING',
    'propagate': False,
}


# ================================================
# SETTINGS.PY — Configuration passerelles de paiement
# Ajoute à la fin (toutes optionnelles, lisent .env)
# ================================================

STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

MONCASH_CLIENT_ID = config('MONCASH_CLIENT_ID', default='')
MONCASH_CLIENT_SECRET = config('MONCASH_CLIENT_SECRET', default='')
MONCASH_MODE = config('MONCASH_MODE', default='sandbox')

PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID', default='')
PAYPAL_CLIENT_SECRET = config('PAYPAL_CLIENT_SECRET', default='')
PAYPAL_MODE = config('PAYPAL_MODE', default='sandbox')


# === Organisation de l'admin Django (regroupement natif) ===
ADMIN_GROUPING = {
    '🎓 Pédagogie': [
        'Ecole', 'Formation', 'Module', 'Lecon', 'Quiz',
        'Parcours', 'Article', 'OutilRecommande', 'Temoignage',
    ],
    '📝 Examens': [
    'Examen', 'QuestionExamen', 'ChoixExamen', 'TentativeExamen',
    ],
    '💳 Paiements & Commandes': [
        'Order', 'OrderItem', 'Transaction', 'Invoice', 'Refund',
        'Coupon', 'Promotion', 'MoyenPaiement', 'AccesFormationDebloque',  'PartenaireAPI',
    ],
    '📬 Contacts': ['Inscription'],
    '👥 Communauté': ['Sujet', 'Reponse', 'Reaction', 'ResultatQuiz'],
    '📊 Abonnements': ['PlanAbonnement', 'Subscription'],
}


# ================================================
# SETTINGS.PY — Django REST Framework
# ================================================

# SETTINGS.PY — Configuration API v2 + Documentation
INSTALLED_APPS += ['drf_spectacular', 'django_filters']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '120/minute',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Blessy Tech Academy API',
    'DESCRIPTION': 'API officielle de la plateforme EdTech Blessy Tech Academy — accès aux formations, articles, progression et écosystème partenaire.',
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {'deepLinking': True, 'persistAuthorization': True},
    'TAGS': [
        {'name': 'Formations', 'description': 'Catalogue de formations'},
        {'name': 'Articles', 'description': 'Knowledge Center'},
        {'name': 'Progression', 'description': "Suivi d'apprentissage étudiant"},
        {'name': 'Auth', 'description': 'Authentification par token'},
    ],
}