# Generated by Django 6.0.6 on 2026-06-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('icone', models.CharField(default='📚', max_length=10)),
                ('description', models.TextField()),
                ('duree_mois', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='academie.formation')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
