# Generated by Django 6.0.6 on 2026-07-18 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="module",
            field=models.ForeignKey(
                blank=True,
                help_text="Quiz spécifique à ce module. Si vide, le quiz reste rattaché à la formation entière.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quiz_module",
                to="academie.module",
            ),
        ),
    ]
