# Generated by Django 6.0.6 on 2026-07-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formation",
            name="illustration",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Émoji d'illustration (💻 🤖 🔐 📈 ...)",
                max_length=10,
            ),
        ),
    ]
