# Generated by Django 6.0.6 on 2026-06-15 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='debouches',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='niveau',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('professionnel', 'Professionnel')], default='debutant', max_length=20),
        ),
        migrations.AddField(
            model_name='formation',
            name='prerequis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='academie.formation'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='sujet',
            field=models.CharField(choices=[('inscription', "S'inscrire à une formation"), ('information', "Demande d'information"), ('partenariat', 'Partenariat'), ('autre', 'Autre')], default='information', max_length=20),
        ),
    ]
