# Generated by Django 6.0.6 on 2026-06-18 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0002_formation_certifications_formation_debouches_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('icone', models.CharField(default='🏫', max_length=10)),
                ('description', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='academie.ecole'),
        ),
    ]
