# Generated by Django 6.0.6 on 2026-07-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0002_quiz_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="formation",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="historicalformation",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
