# Generated by Django 6.0.6 on 2026-06-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0003_ecole_formation_ecole'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['actif'], name='academie_fo_actif_2bdec4_idx'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['niveau'], name='academie_fo_niveau_41a267_idx'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['ecole', 'actif'], name='academie_fo_ecole_i_77c2e2_idx'),
        ),
    ]
