# Generated by Django 6.0.6 on 2026-07-18 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0003_formation_slug_historicalformation_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogRequetePartenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date et heure de la requête"
                    ),
                ),
                (
                    "statut_reponse",
                    models.IntegerField(
                        default=200, help_text="Code HTTP de la réponse (200, 400, 403, 500...)"
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, help_text="URL de l'endpoint appelé", max_length=200
                    ),
                ),
                (
                    "ip_source",
                    models.CharField(
                        blank=True, help_text="Adresse IP d'origine de la requête", max_length=45
                    ),
                ),
                (
                    "partenaire",
                    models.ForeignKey(
                        help_text="Partenaire ayant effectué l'appel",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requetes",
                        to="academie.partenaireapi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Requête Partenaire",
                "verbose_name_plural": "Logs Requêtes Partenaires",
                "ordering": ["-date_creation"],
            },
        ),
    ]
