# Generated by Django 6.0.6 on 2026-07-18 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0004_logrequetepartenaire"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("technique", "💻 Technique"),
                            ("soft_skill", "🤝 Soft Skill"),
                            ("outil", "🛠️ Outil/Logiciel"),
                            ("methode", "📐 Méthodologie"),
                        ],
                        default="technique",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icone", models.CharField(default="⚡", max_length=10)),
                (
                    "formations",
                    models.ManyToManyField(
                        blank=True, related_name="competences", to="academie.formation"
                    ),
                ),
                (
                    "lecons",
                    models.ManyToManyField(
                        blank=True, related_name="competences", to="academie.lecon"
                    ),
                ),
                (
                    "modules",
                    models.ManyToManyField(
                        blank=True, related_name="competences", to="academie.module"
                    ),
                ),
            ],
            options={
                "verbose_name": "Compétence",
                "verbose_name_plural": "Compétences",
                "ordering": ["categorie", "nom"],
            },
        ),
        migrations.CreateModel(
            name="LearningOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Ex: Être capable de créer une API REST avec Django",
                        max_length=300,
                    ),
                ),
                ("ordre", models.IntegerField(default=0)),
                (
                    "competence_associee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academie.competence",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_outcomes",
                        to="academie.formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat d'apprentissage",
                "verbose_name_plural": "Résultats d'apprentissage",
                "ordering": ["ordre"],
            },
        ),
    ]
