# Generated by Django 6.0.6 on 2026-07-19 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0005_competence_learningoutcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="projetetudiant",
            name="formation_liee",
            field=models.ForeignKey(
                blank=True,
                help_text="Formation dans le cadre de laquelle ce projet a été réalisé",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projets_etudiants",
                to="academie.formation",
            ),
        ),
    ]
