# Generated by Django 6.0.6 on 2026-06-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0007_progressionlecon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('icone', models.CharField(default='🎓', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('duree_mois', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('formations', models.ManyToManyField(blank=True, related_name='parcours', to='academie.formation')),
            ],
            options={
                'verbose_name': 'Parcours professionnel',
                'verbose_name_plural': 'Parcours professionnels',
                'ordering': ['ordre', 'titre'],
            },
        ),
    ]
