# Generated by Django 6.0.6 on 2026-07-21 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0007_historiqueconversationia"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
