# Generated by Django 6.0.6 on 2026-07-22 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0008_reaction_content_type_reaction_object_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historiqueconversationia",
            options={"ordering": ["date_creation"]},
        ),
        migrations.RemoveField(
            model_name="profilutilisateur",
            name="derniere_activite",
        ),
        migrations.RemoveField(
            model_name="profilutilisateur",
            name="streak",
        ),
        migrations.RemoveField(
            model_name="profilutilisateur",
            name="xp",
        ),
        migrations.AlterField(
            model_name="logaudit",
            name="objet_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profilutilisateur",
            name="academies",
            field=models.ManyToManyField(
                blank=True, related_name="membres", to="academie.academie"
            ),
        ),
        migrations.AlterField(
            model_name="profilutilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("etudiant", "🎓 Étudiant"),
                    ("formateur", "👨\u200d🏫 Formateur"),
                    ("moderateur", "🛡️ Modérateur Forum"),
                    ("support", "🆘 Support Client"),
                    ("comptable", "💰 Comptable"),
                    ("marketing", "📢 Marketing"),
                    ("admin", "⚙️ Administrateur"),
                ],
                default="etudiant",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profilutilisateur",
            name="specialites",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="profilutilisateur",
            name="taux_remuneration",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterModelTable(
            name="enseignant",
            table="academie_enseignant",
        ),
        migrations.AlterModelTable(
            name="historiqueconversationia",
            table="academie_historiqueconversationia",
        ),
        migrations.AlterModelTable(
            name="logaudit",
            table="academie_logaudit",
        ),
        migrations.AlterModelTable(
            name="profilutilisateur",
            table="academie_profilutilisateur",
        ),
        migrations.CreateModel(
            name="NotificationPushEnvoyee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("badge", "🎖️ Badge"),
                            ("certificat", "🎓 Certificat"),
                            ("forum_reponse", "💬 Réponse forum"),
                            ("rappel_inactivite", "⏰ Rappel"),
                            ("promotion", "🔥 Promotion"),
                            ("systeme", "⚙️ Système"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("corps", models.CharField(max_length=200)),
                ("url_cible", models.CharField(blank=True, max_length=200)),
                ("envoyee_avec_succes", models.BooleanField(default=False)),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_recues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "academie_notificationpushenvoyee",
                "ordering": ["-date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("endpoint", models.URLField(max_length=500)),
                ("cle_p256dh", models.CharField(max_length=200)),
                ("cle_auth", models.CharField(max_length=200)),
                ("navigateur", models.CharField(blank=True, max_length=100)),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "academie_pushsubscription",
                "unique_together": {("utilisateur", "endpoint")},
            },
        ),
    ]
