# Generated by Django 6.0.6 on 2026-06-23 18:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0009_sujet_reponse_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecon',
            name='contenu',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Contenu complet du cours — visible uniquement aux étudiants connectés'),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='contenu',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
