# Generated by Django 6.0.6 on 2026-07-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0009_alter_historiqueconversationia_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilutilisateur",
            name="derniere_activite",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilutilisateur",
            name="streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profilutilisateur",
            name="xp",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profilutilisateur",
            name="academies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Académies auxquelles cet utilisateur a accès (étudiant multi-académie ou formateur multi-académie)",
                related_name="membres",
                to="academie.academie",
            ),
        ),
        migrations.AlterField(
            model_name="profilutilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("etudiant", "Étudiant"),
                    ("parent", "Parent"),
                    ("formateur", "Formateur"),
                    ("asst_formateur", "Assistant Formateur"),
                    ("resp_academique", "Responsable Académique"),
                    ("examinateur", "Examinateur"),
                    ("correcteur", "Correcteur"),
                    ("marketing", "Marketing"),
                    ("support", "Support"),
                    ("finance", "Finance"),
                    ("direction", "Direction"),
                    ("admin", "Administrateur"),
                    ("super_admin", "Super Administrateur"),
                    ("api_client", "API Client"),
                ],
                default="etudiant",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="profilutilisateur",
            name="specialites",
            field=models.CharField(
                blank=True, help_text="Séparées par des virgules", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="profilutilisateur",
            name="taux_remuneration",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="% des ventes reversé", max_digits=5
            ),
        ),
    ]
