# Generated by Django 6.0.6 on 2026-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0010_profilutilisateur_derniere_activite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affilie',
            name='taux_commission',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='utilisations_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valeur',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='numero_facture',
            field=models.CharField(db_index=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='moyenpaiement',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='planabonnement',
            name='avantages',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planabonnement',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='bandeau_texte',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='pourcentage_reduction',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name='accesformationdebloque',
            table='academie_accesformationdebloque',
        ),
        migrations.AlterModelTable(
            name='affilie',
            table='academie_affilie',
        ),
        migrations.AlterModelTable(
            name='commissionaffiliation',
            table='academie_commissionaffiliation',
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='academie_coupon',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='academie_invoice',
        ),
        migrations.AlterModelTable(
            name='moyenpaiement',
            table='academie_moyenpaiement',
        ),
        migrations.AlterModelTable(
            name='order',
            table='academie_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='academie_orderitem',
        ),
        migrations.AlterModelTable(
            name='planabonnement',
            table='academie_planabonnement',
        ),
        migrations.AlterModelTable(
            name='promotion',
            table='academie_promotion',
        ),
        migrations.AlterModelTable(
            name='refund',
            table='academie_refund',
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='academie_subscription',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='academie_transaction',
        ),
    ]
