# Generated by Django 6.0.6 on 2026-06-25 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0010_alter_lecon_contenu_alter_sujet_contenu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_badge', models.CharField(choices=[('premier_post', '✍️ Premier Post'), ('premiere_reponse', '💬 Première Réponse'), ('solution_acceptee', '✅ Solution Acceptée'), ('dix_reponses', '🔥 10 Réponses'), ('cinquante_reponses', '⭐ 50 Réponses'), ('cent_likes', '❤️ 100 Likes reçus'), ('sujet_populaire', '🏆 Sujet Populaire')], max_length=30)),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_forum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge Forum',
                'verbose_name_plural': 'Badges Forum',
                'ordering': ['-date_obtention'],
                'unique_together': {('utilisateur', 'type_badge')},
            },
        ),
    ]
