# Generated by Django 6.0.6 on 2026-06-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0011_badgeforum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='formation',
            name='academie_fo_actif_2bdec4_idx',
        ),
        migrations.RemoveIndex(
            model_name='formation',
            name='academie_fo_niveau_41a267_idx',
        ),
        migrations.RemoveIndex(
            model_name='formation',
            name='academie_fo_ecole_i_77c2e2_idx',
        ),
        migrations.AddField(
            model_name='formation',
            name='gratuit',
            field=models.BooleanField(default=False, help_text="Coche si c'est une formation gratuite (lead magnet)"),
        ),
    ]
