# Generated by Django 6.0.6 on 2026-07-29 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0012_fix_acces_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="examen",
            index=models.Index(fields=["formation"], name="academie_ex_formati_6b4fd4_idx"),
        ),
        migrations.AddIndex(
            model_name="reservationmentorat",
            index=models.Index(fields=["etudiant"], name="academie_re_etudian_354ba2_idx"),
        ),
        migrations.AddIndex(
            model_name="resultatquiz",
            index=models.Index(
                fields=["utilisateur", "quiz"], name="academie_re_utilisa_1e1ae7_idx"
            ),
        ),
    ]
