# Generated by Django 6.0.6 on 2026-06-27 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0012_alter_formation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['nom'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AddField(
            model_name='formation',
            name='formation_upgrade',
            field=models.ForeignKey(blank=True, help_text='Formation payante recommandée à la fin de cette formation gratuite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_gratuites', to='academie.formation'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['actif'], name='academie_fo_actif_2bdec4_idx'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['niveau'], name='academie_fo_niveau_41a267_idx'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['ecole', 'actif'], name='academie_fo_ecole_i_77c2e2_idx'),
        ),
    ]
