# Generated by Django 6.0.6 on 2026-06-28 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0013_alter_formation_options_formation_formation_upgrade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('bienvenue', '👋 Email de Bienvenue'), ('inscription_formation', '📚 Inscription à une formation'), ('rappel_cours', '⏰ Rappel de cours'), ('progression', '📈 Progression de formation'), ('completion', '🎉 Completion de formation'), ('quiz_rappel', '📋 Rappel Quiz'), ('message', '💬 Message'), ('alerte', '⚠️ Alerte')], default='message', max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('email_envoye', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('erreur', models.TextField(blank=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='academie.formation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'lue'], name='academie_no_utilisa_ab1c98_idx'), models.Index(fields=['email_envoye'], name='academie_no_email_e_0d528e_idx'), models.Index(fields=['-date_creation'], name='academie_no_date_cr_9eba44_idx')],
            },
        ),
    ]
