# Generated by Django 6.0.6 on 2026-06-29 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0014_notification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='academie_no_utilisa_ab1c98_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='academie_no_email_e_0d528e_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='academie_no_date_cr_9eba44_idx',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
