# Generated by Django 6.0.6 on 2026-07-30 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0015_notelecon_unique_together"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="OutilRecommande",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("nom", models.CharField(max_length=200)),
                        ("description", models.TextField(max_length=400)),
                        ("url", models.URLField()),
                        ("icone", models.CharField(default="🛠️", max_length=10)),
                        (
                            "categorie",
                            models.CharField(
                                choices=[
                                    ("developpement", "💻 Développement"),
                                    ("design", "🎨 Design"),
                                    ("ia", "🤖 IA"),
                                    ("productivite", "⚡ Productivité"),
                                    ("collaboration", "👥 Collaboration"),
                                    ("securite", "🔐 Sécurité"),
                                ],
                                default="developpement",
                                max_length=20,
                            ),
                        ),
                        ("gratuit", models.BooleanField(default=True)),
                        ("recommande_par_bta", models.BooleanField(default=True)),
                        ("ordre", models.IntegerField(default=0)),
                    ],
                    options={
                        "db_table": "academie_outilrecommande",
                        "ordering": ["ordre", "nom"],
                    },
                ),
                migrations.AlterModelTable(
                    name="academie",
                    table="academie_academie",
                ),
                migrations.AlterModelTable(
                    name="connexionutilisateur",
                    table="academie_connexionutilisateur",
                ),
                migrations.AlterModelTable(
                    name="logrequetepartenaire",
                    table="academie_logrequetepartenaire",
                ),
                migrations.AlterModelTable(
                    name="notification",
                    table="academie_notification",
                ),
                migrations.AlterModelTable(
                    name="partenaireapi",
                    table="academie_partenaireapi",
                ),
                migrations.CreateModel(
                    name="Article",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("titre", models.CharField(max_length=300)),
                        ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                        ("resume", models.TextField(max_length=500)),
                        ("contenu", models.TextField(blank=True)),
                        (
                            "categorie",
                            models.CharField(
                                choices=[
                                    ("guide", "📖 Guide"),
                                    ("tutoriel", "🎓 Tutoriel"),
                                    ("actualite", "📰 Actualité"),
                                    ("conseil", "💡 Conseil"),
                                    ("outil", "🛠️ Outil"),
                                ],
                                default="guide",
                                max_length=20,
                            ),
                        ),
                        (
                            "type_contenu",
                            models.CharField(
                                choices=[
                                    ("article", "📝 Article"),
                                    ("guide", "📖 Guide"),
                                    ("tutoriel", "🎓 Tutoriel"),
                                    ("etude_cas", "📊 Étude de cas"),
                                    ("actualite", "📰 Actualité Tech"),
                                    ("livre_blanc", "📄 Livre blanc"),
                                    ("faq", "❓ FAQ"),
                                ],
                                default="article",
                                max_length=20,
                            ),
                        ),
                        ("en_vedette", models.BooleanField(default=False)),
                        ("publie", models.BooleanField(default=False)),
                        ("temps_lecture", models.IntegerField(default=5)),
                        (
                            "fichier_telechargeable",
                            models.FileField(
                                blank=True, null=True, upload_to="knowledge_center/"
                            ),
                        ),
                        ("nb_vues", models.IntegerField(default=0)),
                        ("nb_partages", models.IntegerField(default=0)),
                        ("meta_titre", models.CharField(blank=True, max_length=70)),
                        ("meta_description", models.CharField(blank=True, max_length=160)),
                        ("mots_cles", models.CharField(blank=True, max_length=255)),
                        ("noindex", models.BooleanField(default=False)),
                        ("date_publication", models.DateTimeField(auto_now_add=True)),
                        ("date_modification", models.DateTimeField(auto_now=True)),
                        (
                            "academie",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="articles",
                                to="academie.academie",
                            ),
                        ),
                        (
                            "articles_associes",
                            models.ManyToManyField(blank=True, to="academie.article"),
                        ),
                        (
                            "auteur",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="articles",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "formation_liee",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="articles",
                                to="academie.formation",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Article",
                        "verbose_name_plural": "Articles",
                        "db_table": "academie_article",
                        "ordering": ["-en_vedette", "-date_publication"],
                    },
                ),
                migrations.CreateModel(
                    name="BadgeForum",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "type_badge",
                            models.CharField(
                                choices=[
                                    ("premier_post", "✍️ Premier Post"),
                                    ("premiere_reponse", "💬 Première Réponse"),
                                    ("solution_acceptee", "✅ Solution Acceptée"),
                                    ("actif_10", "🔥 10 Réponses"),
                                    ("expert_50", "⭐ 50 Réponses"),
                                    ("populaire_100", "❤️ 100 Likes"),
                                ],
                                max_length=30,
                            ),
                        ),
                        ("date_obtention", models.DateTimeField(auto_now_add=True)),
                        (
                            "utilisateur",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="badges_forum",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Badge Forum",
                        "verbose_name_plural": "Badges Forum",
                        "db_table": "academie_badgeforum",
                        "ordering": ["-date_obtention"],
                        "unique_together": {("utilisateur", "type_badge")},
                    },
                ),
                migrations.CreateModel(
                    name="Certificat",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "numero",
                            models.CharField(
                                blank=True, db_index=True, max_length=50, unique=True
                            ),
                        ),
                        ("date_emission", models.DateTimeField(auto_now_add=True)),
                        (
                            "fichier_pdf",
                            models.FileField(blank=True, null=True, upload_to="certificats/"),
                        ),
                        (
                            "examen_origine",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="academie.examen",
                            ),
                        ),
                        (
                            "formation",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="academie.formation",
                            ),
                        ),
                        (
                            "utilisateur",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="certificats",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Certificat",
                        "verbose_name_plural": "Certificats",
                        "db_table": "academie_certificat",
                    },
                ),
                migrations.CreateModel(
                    name="Inscription",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("prenom", models.CharField(max_length=100)),
                        ("nom", models.CharField(max_length=100)),
                        ("email", models.EmailField(max_length=254)),
                        ("telephone", models.CharField(blank=True, max_length=20)),
                        (
                            "sujet",
                            models.CharField(
                                choices=[
                                    ("inscription", "S'inscrire à une formation"),
                                    ("information", "Demande d'information"),
                                    ("partenariat", "Partenariat"),
                                    ("autre", "Autre"),
                                ],
                                default="information",
                                max_length=20,
                            ),
                        ),
                        ("message", models.TextField()),
                        ("date_inscription", models.DateTimeField(auto_now_add=True)),
                        ("traite", models.BooleanField(default=False)),
                        (
                            "statut_lead",
                            models.CharField(
                                choices=[
                                    ("nouveau", "🆕 Nouveau"),
                                    ("contacte", "📞 Contacté"),
                                    ("interesse", "💬 Intéressé"),
                                    ("converti", "✅ Converti"),
                                    ("perdu", "❌ Perdu"),
                                ],
                                default="nouveau",
                                max_length=15,
                            ),
                        ),
                        (
                            "source_lead",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("site", "Site web"),
                                    ("forum", "Forum"),
                                    ("reseaux", "Réseaux sociaux"),
                                    ("bouche_oreille", "Bouche-à-oreille"),
                                    ("autre", "Autre"),
                                ],
                                default="site",
                                max_length=50,
                            ),
                        ),
                        (
                            "notes_internes",
                            models.TextField(
                                blank=True,
                                help_text="Notes visibles uniquement par l'équipe",
                            ),
                        ),
                        (
                            "assigne_a",
                            models.ForeignKey(
                                blank=True,
                                help_text="Membre de l'équipe responsable de ce lead",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="leads_assignes",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "formation",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="inscriptions",
                                to="academie.formation",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Inscription",
                        "verbose_name_plural": "Inscriptions",
                        "db_table": "academie_inscription",
                        "ordering": ["-date_inscription"],
                    },
                ),
                migrations.CreateModel(
                    name="InteractionCRM",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "type_interaction",
                            models.CharField(
                                choices=[
                                    ("appel", "📞 Appel"),
                                    ("email", "📧 Email"),
                                    ("whatsapp", "💬 WhatsApp"),
                                    ("rencontre", "🤝 Rencontre"),
                                    ("note", "📝 Note"),
                                ],
                                default="note",
                                max_length=15,
                            ),
                        ),
                        ("contenu", models.TextField()),
                        ("date_creation", models.DateTimeField(auto_now_add=True)),
                        (
                            "auteur",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "inscription",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="interactions",
                                to="academie.inscription",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Interaction CRM",
                        "verbose_name_plural": "Interactions CRM",
                        "db_table": "academie_interactioncrm",
                        "ordering": ["-date_creation"],
                    },
                ),
                migrations.CreateModel(
                    name="ProjetEtudiant",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("titre", models.CharField(max_length=200)),
                        ("description", models.TextField()),
                        ("technologies", models.CharField(blank=True, max_length=300)),
                        ("lien", models.URLField(blank=True, null=True)),
                        (
                            "image",
                            models.ImageField(blank=True, null=True, upload_to="projets/"),
                        ),
                        ("date_creation", models.DateTimeField(auto_now_add=True)),
                        (
                            "auteur",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="projets",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "competences_demontrees",
                            models.ManyToManyField(
                                blank=True,
                                related_name="projets_demonstrations",
                                to="academie.competence",
                            ),
                        ),
                        (
                            "formation_liee",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="projets_realises",
                                to="academie.formation",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Projet Étudiant",
                        "verbose_name_plural": "Projets Étudiants",
                        "db_table": "academie_projetetudiant",
                        "ordering": ["-date_creation"],
                    },
                ),
                migrations.CreateModel(
                    name="Sujet",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("titre", models.CharField(max_length=200)),
                        ("contenu", models.TextField()),
                        (
                            "categorie",
                            models.CharField(
                                choices=[
                                    ("general", "Général"),
                                    ("aide", "Aide"),
                                    ("projet", "Projet"),
                                    ("emploi", "Emploi"),
                                ],
                                default="general",
                                max_length=20,
                            ),
                        ),
                        ("vues", models.IntegerField(default=0)),
                        ("epingle", models.BooleanField(default=False)),
                        ("resolu", models.BooleanField(default=False)),
                        ("date_creation", models.DateTimeField(auto_now_add=True)),
                        ("date_modification", models.DateTimeField(auto_now=True)),
                        (
                            "auteur",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="sujets",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "formation",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="academie.formation",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Sujet",
                        "verbose_name_plural": "Sujets",
                        "db_table": "academie_sujet",
                        "ordering": ["-epingle", "-date_creation"],
                    },
                ),
                migrations.CreateModel(
                    name="Reponse",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("contenu", models.TextField()),
                        ("acceptee", models.BooleanField(default=False)),
                        ("date_creation", models.DateTimeField(auto_now_add=True)),
                        (
                            "auteur",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "sujet",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="reponses",
                                to="academie.sujet",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Réponse",
                        "verbose_name_plural": "Réponses",
                        "db_table": "academie_reponse",
                        "ordering": ["date_creation"],
                    },
                ),
                migrations.CreateModel(
                    name="Reaction",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "object_id",
                            models.PositiveBigIntegerField(blank=True, null=True),
                        ),
                        ("date_creation", models.DateTimeField(auto_now_add=True)),
                        (
                            "content_type",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="contenttypes.contenttype",
                            ),
                        ),
                        (
                            "utilisateur",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "reponse",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="academie.reponse",
                            ),
                        ),
                        (
                            "sujet",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="academie.sujet",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Réaction",
                        "verbose_name_plural": "Réactions",
                        "db_table": "academie_reaction",
                    },
                ),
                migrations.CreateModel(
                    name="Temoignage",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("prenom_nom", models.CharField(max_length=200)),
                        ("texte", models.TextField()),
                        (
                            "note",
                            models.IntegerField(
                                choices=[
                                    (1, "1 étoile"),
                                    (2, "2 étoiles"),
                                    (3, "3 étoiles"),
                                    (4, "4 étoiles"),
                                    (5, "5 étoiles"),
                                ],
                                default=5,
                            ),
                        ),
                        ("initiales", models.CharField(max_length=3)),
                        (
                            "titre_professionnel",
                            models.CharField(blank=True, max_length=200),
                        ),
                        ("en_vedette", models.BooleanField(default=False)),
                        ("approuve", models.BooleanField(default=False)),
                        ("date_creation", models.DateTimeField(auto_now_add=True)),
                        (
                            "formation_suivie",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="temoignages",
                                to="academie.formation",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "academie_temoignage",
                        "ordering": ["-en_vedette", "-date_creation"],
                    },
                ),
                migrations.DeleteModel(
                    name="HistoricalArticle",
                ),
                migrations.AddIndex(
                    model_name="sujet",
                    index=models.Index(
                        fields=["categorie", "date_creation"],
                        name="academie_su_categor_a8dcbb_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="sujet",
                    index=models.Index(
                        fields=["formation"], name="academie_su_formati_e4eaae_idx"
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="reaction",
                    unique_together={("utilisateur", "reponse"), ("utilisateur", "sujet")},
                ),
            ],
        ),
    ]