# Generated by Django 6.0.6 on 2026-07-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0016_outilrecommande_alter_academie_table_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pourcentage_reduction__gt", 0), ("pourcentage_reduction__lte", 100)
                ),
                name="promotion_pourcentage_valide",
            ),
        ),
    ]
