# Generated by Django 6.0.6 on 2026-06-30 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0016_alter_badgeforum_type_badge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/')),
                ('lien', models.URLField(blank=True, null=True)),
                ('technologies', models.CharField(blank=True, help_text='Ex: Python, Django, React', max_length=300)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet étudiant',
                'verbose_name_plural': 'Projets étudiants',
                'ordering': ['-date_creation'],
            },
        ),
    ]
