# Generated by Django 6.0.6 on 2026-07-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0017_projetetudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='message_partage',
            field=models.CharField(blank=True, default='', help_text='Message utilisé pour le partage automatique sur les réseaux sociaux. Laissez vide pour générer automatiquement.', max_length=500),
        ),
    ]
