# Generated by Django 6.0.6 on 2026-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0017_promotion_promotion_pourcentage_valide"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="orderitem_type_produit_coherent",
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type_produit", "formation"), ("formation__isnull", False)),
                    models.Q(("type_produit", "parcours"), ("parcours__isnull", False)),
                    _connector="OR",
                ),
                name="orderitem_produit_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("prix_unitaire__gte", 0)), name="orderitem_prix_positif"
            ),
        ),
    ]
