# Generated by Django 6.0.6 on 2026-07-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0018_remove_orderitem_orderitem_type_produit_coherent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificat",
            name="numero",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=50, unique=True
            ),
        ),
    ]
