# Generated by Django 6.0.6 on 2026-07-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0018_formation_message_partage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='illustration',
            field=models.CharField(blank=True, default='', help_text="Émoji d'illustration moderne (ex: 💻, 📈, 🔐)", max_length=10),
        ),
    ]
