# Generated by Django ...
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0021_add_fichier_pdf_to_certificat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='numero',
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=50,
                unique=True,
            ),
        ),
    ]