# Generated by Django 6.0.6 on 2026-07-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0021_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeforum',
            name='type_badge',
            field=models.CharField(choices=[('premier_post', '✍️ Premier Post'), ('premiere_reponse', '💬 Première Réponse'), ('solution_acceptee', '✅ Solution Acceptée'), ('dix_reponses', '🔥 10 Réponses'), ('cinquante_reponses', '⭐ 50 Réponses'), ('cent_likes', '❤️ 100 Likes reçus'), ('sujet_populaire', '🏆 Sujet Populaire'), ('premier_quiz', '🏅 Premier Quiz Réussi'), ('cinq_quiz', '📝 5 Quiz Réussis'), ('dix_heures', "⏰ 10 Heures d'Apprentissage"), ('cinquante_heures', "🎯 50 Heures d'Apprentissage"), ('premiere_formation', '🎓 Première Formation Complétée'), ('trois_formations', '🏆 3 Formations Complétées'), ('premier_cours_termine', '🏅 Premier cours terminé'), ('cinq_lecons', '📚 5 leçons terminées'), ('dix_lecons', '📘 10 leçons terminées'), ('expert_python', '🐍 Expert Python'), ('expert_web', '🌐 Expert Web'), ('expert_data', '📊 Expert Données'), ('expert_cyber', '🔒 Expert Cybersécurité'), ('expert_design', '🎨 Expert Design'), ('expert_excel', '📊 Expert Excel'), ('expert_ia', '🤖 Expert IA'), ('projet_termine', '🚀 Projet Terminé'), ('trois_projets', '💼 3 Projets Livrés'), ('profile_complet', '👤 Profil Complété'), ('premier_certificat', '📜 Premier Certificat'), ('membre_actif', '🌟 Membre Actif'), ('membre_actif_forum', '💬 Membre actif du forum')], max_length=30),
        ),
    ]
