# Generated by Django 6.0.6 on 2026-07-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0022_alter_numero_certificat_length"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="orderitem_produit_coherent",
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("type_produit", "formation"),
                        ("formation__isnull", False),
                        ("parcours__isnull", True),
                    ),
                    models.Q(
                        ("type_produit", "parcours"),
                        ("formation__isnull", True),
                        ("parcours__isnull", False),
                    ),
                    models.Q(("formation__isnull", True), ("parcours__isnull", True)),
                    _connector="OR",
                ),
                name="orderitem_produit_coherent",
            ),
        ),
    ]
