# Generated by Django 6.0.6 on 2026-07-05 16:52

import datetime
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0024_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutilRecommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=400)),
                ('url', models.URLField()),
                ('icone', models.CharField(default='🛠️', max_length=10)),
                ('categorie', models.CharField(choices=[('developpement', '💻 Développement'), ('design', '🎨 Design'), ('ia', '🤖 Intelligence Artificielle'), ('productivite', '⚡ Productivité'), ('collaboration', '👥 Collaboration'), ('securite', '🔐 Sécurité')], default='developpement', max_length=20)),
                ('gratuit', models.BooleanField(default=True)),
                ('recommande_par_bta', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Outil recommandé',
                'verbose_name_plural': 'Outils recommandés',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-en_vedette', '-date_publication'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('guide', '📖 Guide'), ('tutoriel', '🎓 Tutoriel'), ('actualite', '📰 Actualité'), ('conseil', '💡 Conseil'), ('outil', '🛠️ Outil')], default='guide', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='en_vedette',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='formation_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='academie.formation'),
        ),
        migrations.AddField(
            model_name='article',
            name='publie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='temps_lecture',
            field=models.IntegerField(default=5, help_text='Temps de lecture estimé en minutes'),
        ),
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 5, 12, 52, 44, 337066)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='resume',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_nom', models.CharField(max_length=200)),
                ('texte', models.TextField()),
                ('note', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], default=5)),
                ('initiales', models.CharField(help_text='Ex: JRB pour Jean Raymond BELONY', max_length=3)),
                ('titre_professionnel', models.CharField(blank=True, help_text='Ex: Développeur Web Freelance', max_length=200)),
                ('en_vedette', models.BooleanField(default=False)),
                ('approuve', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('formation_suivie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temoignages', to='academie.formation')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-en_vedette', '-date_creation'],
            },
        ),
    ]
