# Generated by Django 6.0.6 on 2026-07-31 06:01

import academie.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0025_add_verifie_field_to_certificat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academie",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="logos/",
                validators=[academie.validators.valider_image],
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="fichier_telechargeable",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="knowledge_center/",
                validators=[academie.validators.valider_document],
            ),
        ),
        migrations.AlterField(
            model_name="certificat",
            name="fichier_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="certificats/",
                validators=[academie.validators.valider_document],
            ),
        ),
        migrations.AlterField(
            model_name="enseignant",
            name="document_cv",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="enseignants/cv/",
                validators=[academie.validators.valider_document],
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="fichier_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="factures/",
                validators=[academie.validators.valider_document],
            ),
        ),
        migrations.AlterField(
            model_name="projetetudiant",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projets/",
                validators=[academie.validators.valider_image],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="preuve_paiement",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="preuves_paiement/",
                validators=[academie.validators.valider_preuve_paiement],
            ),
        ),
        migrations.CreateModel(
            name="AlerteFraude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("faible", "🟡 Faible"),
                            ("moyen", "🟠 Moyen"),
                            ("eleve", "🔴 Élevé"),
                        ],
                        max_length=10,
                    ),
                ),
                ("raison", models.TextField()),
                ("revue_par_admin", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes_fraude",
                        to="academie.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte fraude",
                "verbose_name_plural": "Alertes fraude",
                "db_table": "academie_alertefraude",
                "ordering": ["-date_creation"],
            },
        ),
    ]
