# Generated by Django 6.0.6 on 2026-07-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0025_outilrecommande_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetetudiant',
            name='competences_developpees',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='projetetudiant',
            name='niveau_difficulte',
            field=models.CharField(blank=True, choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20),
        ),
    ]
