# Generated by Django 6.0.6 on 2026-07-31 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0026_alter_academie_logo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examen",
            name="competences_liees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Compétences validées automatiquement si l'étudiant réussit cet examen",
                related_name="examens_lies",
                to="academie.competence",
            ),
        ),
        migrations.CreateModel(
            name="CompetenceValidee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("examen", "🎯 Examen réussi"),
                            ("quiz", "📝 Quiz réussi"),
                            ("projet", "💼 Projet évalué par un formateur"),
                            ("formation_completee", "🎓 Formation terminée à 100%"),
                            (
                                "validation_manuelle",
                                "✍️ Validée manuellement par un admin/formateur",
                            ),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("acquis", "✅ Acquis"),
                            ("confirme", "⭐ Confirmé"),
                            ("expert", "🏆 Expert"),
                        ],
                        default="acquis",
                        max_length=15,
                    ),
                ),
                (
                    "score_obtenu",
                    models.IntegerField(
                        blank=True,
                        help_text="Score/pourcentage au moment de la validation, si applicable",
                        null=True,
                    ),
                ),
                ("date_validation", models.DateTimeField(auto_now_add=True)),
                (
                    "competence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="academie.competence",
                    ),
                ),
                (
                    "examen_origine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competences_declenchees",
                        to="academie.examen",
                    ),
                ),
                (
                    "formation_origine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academie.formation",
                    ),
                ),
                (
                    "projet_origine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academie.projetetudiant",
                    ),
                ),
                (
                    "quiz_origine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academie.quiz",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competences_validees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competences_validees_par_moi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compétence validée",
                "verbose_name_plural": "Compétences validées",
                "ordering": ["-date_validation"],
                "indexes": [
                    models.Index(
                        fields=["utilisateur", "competence"], name="academie_co_utilisa_406c25_idx"
                    ),
                    models.Index(
                        fields=["utilisateur", "date_validation"],
                        name="academie_co_utilisa_3ed4ed_idx",
                    ),
                ],
                "unique_together": {
                    ("utilisateur", "competence", "source_type", "examen_origine", "quiz_origine")
                },
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='projetetudiant',
                    name='niveau_difficulte',
                    field=models.CharField(default='debutant', max_length=20),
                ),
            ],
        ),
    ]