# Generated by Django 6.0.6 on 2026-07-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0026_projetetudiant_competences_developpees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description SEO (150-160 caractères recommandés)', max_length=160),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_titre',
            field=models.CharField(blank=True, help_text='Titre SEO (60-70 caractères recommandés)', max_length=70),
        ),
        migrations.AddField(
            model_name='article',
            name='mots_cles',
            field=models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='noindex',
            field=models.BooleanField(default=False, help_text="Empêcher l'indexation Google"),
        ),
    ]
