# Generated by Django 6.0.6 on 2026-07-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0027_article_meta_description_article_meta_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='limite_temps_minutes',
            field=models.IntegerField(default=0, help_text='0 = pas de limite'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='melanger_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='melanger_reponses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='tentatives_max',
            field=models.IntegerField(default=0, help_text='0 = illimité'),
        ),
    ]
