# Generated by Django 6.0.6 on 2026-07-07 23:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0028_quiz_limite_temps_minutes_quiz_melanger_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEcole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('icone', models.CharField(default='🏫', max_length=10)),
                ('description', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical École',
                'verbose_name_plural': 'historical Écoles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFormation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('icone', models.CharField(default='📚', max_length=10)),
                ('illustration', models.CharField(blank=True, default='', help_text="Émoji d'illustration moderne (ex: 💻, 📈, 🔐)", max_length=10)),
                ('description', models.TextField()),
                ('duree_mois', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('professionnel', 'Professionnel')], default='debutant', max_length=20)),
                ('debouches', models.TextField(blank=True)),
                ('prerequis', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('message_partage', models.CharField(blank=True, default='', help_text='Message utilisé pour le partage automatique sur les réseaux sociaux. Laissez vide pour générer automatiquement.', max_length=500)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('gratuit', models.BooleanField(default=False, help_text="Coche si c'est une formation gratuite (lead magnet)")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ecole', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academie.ecole')),
                ('formation_upgrade', models.ForeignKey(blank=True, db_constraint=False, help_text='Formation payante recommandée à la fin de cette formation gratuite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academie.formation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Formation',
                'verbose_name_plural': 'historical Formations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
