# Generated by Django 6.0.6 on 2026-07-08 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0029_historicalecole_historicalformation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnexionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField()),
                ('navigateur', models.CharField(max_length=300)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('suspecte', models.BooleanField(default=False)),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connexion utilisateur',
                'verbose_name_plural': 'Connexions utilisateurs',
                'ordering': ['-date_connexion'],
            },
        ),
    ]
