# Generated by Django 6.0.6 on 2026-07-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0030_add_m2m_competences_demontrees"),
    ]

    operations = [
        migrations.AddField(
            model_name="formation",
            name="sequentiel_obligatoire",
            field=models.BooleanField(
                default=False,
                help_text="Si activé, l'étudiant doit terminer chaque leçon dans l'ordre avant d'accéder à la suivante",
            ),
        ),
    ]
