# Generated by Django 6.0.6 on 2026-07-10 02:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0030_connexionutilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('manuel', 'Paiement manuel (validation admin)'), ('moncash', 'MonCash'), ('natcash', 'NatCash'), ('stripe', 'Carte bancaire (Stripe)'), ('paypal', 'PayPal'), ('virement', 'Virement bancaire')], max_length=20, unique=True)),
                ('nom_affiche', models.CharField(max_length=100)),
                ('icone', models.CharField(default='💳', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, help_text="Instructions affichées à l'étudiant (ex: numéro MonCash à utiliser)")),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Moyen de paiement',
                'verbose_name_plural': 'Moyens de paiement',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('type_reduction', models.CharField(choices=[('fixe', 'Montant fixe'), ('pourcentage', 'Pourcentage')], default='pourcentage', max_length=15)),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Montant $ ou % selon le type', max_digits=10)),
                ('utilisations_max', models.IntegerField(default=0, help_text='0 = illimité')),
                ('utilisations_actuelles', models.IntegerField(default=0)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('ecole_specifique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='academie.ecole')),
                ('formation_specifique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='academie.formation')),
                ('parcours_specifique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='academie.parcours')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reduction_totale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('HTG', 'HTG')], default='USD', max_length=3)),
                ('statut', models.CharField(choices=[('en_attente', '⏳ En attente de paiement'), ('paye', '✅ Payée'), ('annule', '❌ Annulée'), ('rembourse', '↩️ Remboursée')], default='en_attente', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('coupon_applique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academie.coupon')),
                ('moyen_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academie.moyenpaiement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='academie.order')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_produit', models.CharField(choices=[('formation', 'Formation'), ('parcours', 'Parcours Professionnel')], max_length=15)),
                ('nom_produit_snapshot', models.CharField(max_length=200)),
                ('icone_produit_snapshot', models.CharField(default='📚', max_length=10)),
                ('ecole_nom_snapshot', models.CharField(blank=True, max_length=200)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academie.order')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academie.formation')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academie.parcours')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('pourcentage_reduction', models.IntegerField(help_text='Ex: 30 pour -30%')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('actif', models.BooleanField(default=True)),
                ('bandeau_texte', models.CharField(blank=True, help_text="Ex: 🔥 -30% jusqu'au 30 novembre", max_length=200)),
                ('ecoles_concernees', models.ManyToManyField(blank=True, related_name='promotions', to='academie.ecole')),
                ('formations_concernees', models.ManyToManyField(blank=True, related_name='promotions', to='academie.formation')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raison', models.TextField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='demande', max_length=15)),
                ('approuve_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='academie.order')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_externe', models.CharField(blank=True, help_text='ID transaction MonCash/Stripe/etc.', max_length=100)),
                ('preuve_paiement', models.ImageField(blank=True, null=True, upload_to='preuves_paiement/')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('initiee', 'Initiée'), ('reussie', 'Réussie'), ('echouee', 'Échouée'), ('en_verification', 'En vérification manuelle')], default='initiee', max_length=20)),
                ('notes_admin', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='academie.order')),
                ('moyen_paiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academie.moyenpaiement')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AccesFormationDebloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_formation_snapshot', models.CharField(max_length=200)),
                ('date_deblocage', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academie.formation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_debloques', to=settings.AUTH_USER_MODEL)),
                ('commande_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academie.order')),
            ],
            options={
                'verbose_name': 'Accès formation débloqué',
                'verbose_name_plural': 'Accès formations débloqués',
                'unique_together': {('utilisateur', 'nom_formation_snapshot')},
            },
        ),
    ]
