# Generated by Django 6.0.6 on 2026-07-31 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0031_formation_sequentiel_obligatoire"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SoumissionProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("lien_livrable", models.URLField(help_text="Lien GitHub, Figma, démo, etc.")),
                (
                    "fichier_livrable",
                    models.FileField(blank=True, null=True, upload_to="soumissions_projets/"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "⏳ En attente d'évaluation"),
                            ("validee", "✅ Validée"),
                            ("a_revoir", "🔄 À revoir"),
                            ("refusee", "❌ Refusée"),
                        ],
                        default="en_attente",
                        max_length=15,
                    ),
                ),
                ("feedback_formateur", models.TextField(blank=True)),
                ("note_sur_20", models.IntegerField(blank=True, null=True)),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                ("date_evaluation", models.DateTimeField(blank=True, null=True)),
                (
                    "competences_a_valider",
                    models.ManyToManyField(
                        blank=True, related_name="soumissions_liees", to="academie.competence"
                    ),
                ),
                (
                    "evalue_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projets_evalues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soumissions",
                        to="academie.formation",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academie.module",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soumissions_projets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Soumission de projet",
                "verbose_name_plural": "Soumissions de projets",
                "ordering": ["-date_soumission"],
                "indexes": [
                    models.Index(fields=["statut"], name="academie_so_statut_5949c2_idx"),
                    models.Index(fields=["utilisateur"], name="academie_so_utilisa_fbcf77_idx"),
                ],
            },
        ),
    ]
