# Generated by Django 6.0.6 on 2026-07-10 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0031_moyenpaiement_coupon_order_invoice_orderitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicite', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], default='mensuel', max_length=10)),
                ('avantages', models.TextField(help_text='Un avantage par ligne')),
                ('actif', models.BooleanField(default=True)),
                ('stripe_price_id', models.CharField(blank=True, help_text='ID prix Stripe (price_xxx)', max_length=100)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_nom_snapshot', models.CharField(max_length=100)),
                ('prix_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('annule', 'Annulé'), ('expire', 'Expiré'), ('en_echec', 'Paiement échoué')], default='actif', max_length=15)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_prochain_renouvellement', models.DateTimeField()),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('renouvellement_auto', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academie.planabonnement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
    ]
