# Generated by Django 6.0.6 on 2026-07-11 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0032_planabonnement_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duree_minutes', models.IntegerField(default=60)),
                ('seuil_reussite', models.IntegerField(default=70, help_text='Pourcentage minimum pour réussir')),
                ('tentatives_max', models.IntegerField(default=3)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='academie.formation')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
            },
        ),
        migrations.CreateModel(
            name='QuestionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('type_question', models.CharField(choices=[('qcm', 'QCM'), ('vrai_faux', 'Vrai/Faux'), ('texte', 'Réponse texte')], default='qcm', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=1)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academie.examen')),
            ],
            options={
                'verbose_name': "Question d'examen",
                'verbose_name_plural': "Questions d'examen",
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ChoixExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
                ('est_correct', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='academie.questionexamen')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TentativeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('reussi', models.BooleanField(blank=True, null=True)),
                ('evenements_suspects', models.JSONField(default=list)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='academie.examen')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_examens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Tentative d'examen",
                'verbose_name_plural': "Tentatives d'examens",
            },
        ),
    ]
