# Generated by Django 6.0.7 on 2026-08-01 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0032_soumissionprojet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohorte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(help_text="Ex: Cohorte Pilote 2026", max_length=150)),
                ("date_debut", models.DateField()),
                ("date_fin_prevue", models.DateField()),
                ("actif", models.BooleanField(default=True)),
                (
                    "formations",
                    models.ManyToManyField(related_name="cohortes", to="academie.formation"),
                ),
                (
                    "membres",
                    models.ManyToManyField(
                        blank=True, related_name="cohortes", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Cohorte",
                "verbose_name_plural": "Cohortes",
                "ordering": ["-date_debut"],
            },
        ),
    ]
