# Generated by Django 6.0.7 on 2026-08-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0033_cohorte"),
    ]

    operations = [
        migrations.AddField(
            model_name="temoignage",
            name="statut",
            field=models.CharField(
                choices=[
                    ("demande", "Demande envoyée"),
                    ("consenti", "Consentement obtenu"),
                    ("redige", "Rédigé"),
                    ("valide", "Validé par admin"),
                    ("publie", "Publié"),
                ],
                default="redige",
                max_length=15,
            ),
        ),
    ]
