# Generated by Django 6.0.6 on 2026-07-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0033_examen_questionexamen_choixexamen_tentativeexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='certificat_auto',
            field=models.BooleanField(default=True, help_text='Générer certificat si réussite'),
        ),
        migrations.AddField(
            model_name='examen',
            name='competences_evaluees',
            field=models.TextField(blank=True, help_text='Compétences évaluées (une par ligne)'),
        ),
        migrations.AddField(
            model_name='examen',
            name='conditions_utilisation',
            field=models.TextField(blank=True, help_text="Conditions à accepter avant l'examen"),
        ),
        migrations.AddField(
            model_name='examen',
            name='date_disponibilite',
            field=models.DateTimeField(blank=True, help_text="Date d'ouverture", null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='date_expiration',
            field=models.DateTimeField(blank=True, help_text='Date de fermeture', null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='prerequis_examen',
            field=models.TextField(blank=True, help_text="Prérequis pour passer l'examen"),
        ),
        migrations.AddField(
            model_name='examen',
            name='xp_recompense',
            field=models.IntegerField(default=100, help_text='XP gagnés si réussite'),
        ),
        migrations.AddField(
            model_name='tentativeexamen',
            name='bonnes_reponses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tentativeexamen',
            name='mauvaises_reponses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tentativeexamen',
            name='questions_repondues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tentativeexamen',
            name='temps_utilise_secondes',
            field=models.IntegerField(blank=True, help_text='Temps total utilisé', null=True),
        ),
    ]
