# Generated by Django 6.0.6 on 2026-07-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0034_examen_certificat_auto_examen_competences_evaluees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articles_associes',
            field=models.ManyToManyField(blank=True, to='academie.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='fichier_telechargeable',
            field=models.FileField(blank=True, null=True, upload_to='knowledge_center/'),
        ),
        migrations.AddField(
            model_name='article',
            name='nb_partages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='nb_vues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='type_contenu',
            field=models.CharField(choices=[('article', '📝 Article'), ('guide', '📖 Guide'), ('tutoriel', '🎓 Tutoriel'), ('etude_cas', '📊 Étude de cas'), ('actualite', '📰 Actualité Tech'), ('livre_blanc', '📄 Livre blanc'), ('faq', '❓ FAQ')], default='article', max_length=20),
        ),
    ]
