# Generated by Django 6.0.7 on 2026-08-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0034_temoignage_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificat",
            name="duree_heures",
            field=models.IntegerField(
                default=0, help_text="Durée totale de la formation en heures"
            ),
        ),
        migrations.AddField(
            model_name="certificat",
            name="niveau",
            field=models.CharField(
                choices=[
                    ("initiation", "Initiation"),
                    ("intermediaire", "Intermédiaire"),
                    ("avance", "Avancé"),
                ],
                default="initiation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="certificat",
            name="qr_code_image",
            field=models.ImageField(blank=True, null=True, upload_to="certificats/qr/"),
        ),
        migrations.AddField(
            model_name="certificat",
            name="resultat_final",
            field=models.IntegerField(
                blank=True, help_text="Score/pourcentage final si examen", null=True
            ),
        ),
        migrations.AddField(
            model_name="certificat",
            name="statut",
            field=models.CharField(
                choices=[
                    ("valide", "✅ Valide"),
                    ("revoque", "❌ Révoqué"),
                    ("expire", "⏳ Expiré"),
                ],
                default="valide",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="examen",
            name="type_evaluation",
            field=models.CharField(
                choices=[
                    ("formative", "📝 Formative (auto-évaluation, sans impact certificat)"),
                    ("sommative", "🎯 Sommative (compte pour la validation de compétence)"),
                    ("finale", "🏆 Examen final (déclenche la certification)"),
                ],
                default="sommative",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="projetetudiant",
            name="outils_utilises",
            field=models.CharField(
                blank=True, help_text="Outils/langages utilisés (détaillé)", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="projetetudiant",
            name="probleme_traite",
            field=models.TextField(blank=True, help_text="Quel problème le projet résout-il ?"),
        ),
        migrations.AddField(
            model_name="projetetudiant",
            name="resultat",
            field=models.TextField(blank=True, help_text="Résultat concret obtenu"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="type_evaluation",
            field=models.CharField(
                choices=[
                    ("formative", "📝 Formative (auto-évaluation, sans impact certificat)"),
                    ("sommative", "🎯 Sommative (compte pour la validation de compétence)"),
                    ("finale", "🏆 Examen final (déclenche la certification)"),
                ],
                default="formative",
                max_length=15,
            ),
        ),
    ]
