# Generated by Django 6.0.7 on 2026-08-01 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0035_certificat_duree_heures_certificat_niveau_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="projetetudiant",
            old_name="resultat",
            new_name="resultat_obtenu",
        ),
        migrations.AddField(
            model_name="projetetudiant",
            name="date_validation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projetetudiant",
            name="valide_par_formateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projets_valides_par_moi",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projetetudiant",
            name="outils_utilises",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="projetetudiant",
            name="probleme_traite",
            field=models.TextField(blank=True, help_text="Quel problème ce projet résout-il ?"),
        ),
    ]
