# Generated by Django 6.0.6 on 2026-07-12 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0035_article_articles_associes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='certification_obtenue',
            field=models.CharField(blank=True, help_text='Nom du certificat délivré', max_length=255),
        ),
        migrations.AddField(
            model_name='formation',
            name='competences_acquises',
            field=models.TextField(blank=True, help_text='Une compétence par ligne'),
        ),
        migrations.AddField(
            model_name='formation',
            name='competences_cles',
            field=models.TextField(blank=True, help_text='Compétences clés (une par ligne)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='logiciels_maitrises',
            field=models.TextField(blank=True, help_text='Logiciels ou outils maîtrisés (un par ligne)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='metiers',
            field=models.TextField(blank=True, help_text='Un métier par ligne'),
        ),
        migrations.AddField(
            model_name='formation',
            name='niveau_sortie',
            field=models.CharField(blank=True, help_text='Ex : Développeur Backend Junior', max_length=120),
        ),
        migrations.AddField(
            model_name='formation',
            name='outils_utilises',
            field=models.TextField(blank=True, help_text='Technologies utilisées durant la formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='projets_realises',
            field=models.TextField(blank=True, help_text='Un projet réalisé par ligne'),
        ),
        migrations.AddField(
            model_name='formation',
            name='salaire_haiti',
            field=models.CharField(blank=True, help_text='Ex : 40 000 à 120 000 HTG/mois', max_length=60),
        ),
        migrations.AddField(
            model_name='formation',
            name='salaire_international',
            field=models.CharField(blank=True, help_text='Ex : 2 000 à 6 000 USD/mois', max_length=60),
        ),
        migrations.AddField(
            model_name='formation',
            name='taux_employabilite',
            field=models.PositiveIntegerField(default=0, help_text='Pourcentage estimé'),
        ),
        migrations.AddField(
            model_name='formation',
            name='temps_pour_emploi',
            field=models.CharField(blank=True, help_text='Ex : 3 à 6 mois', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='certification_obtenue',
            field=models.CharField(blank=True, help_text='Nom du certificat délivré', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='competences_acquises',
            field=models.TextField(blank=True, help_text='Une compétence par ligne'),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='competences_cles',
            field=models.TextField(blank=True, help_text='Compétences clés (une par ligne)'),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='logiciels_maitrises',
            field=models.TextField(blank=True, help_text='Logiciels ou outils maîtrisés (un par ligne)'),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='metiers',
            field=models.TextField(blank=True, help_text='Un métier par ligne'),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='niveau_sortie',
            field=models.CharField(blank=True, help_text='Ex : Développeur Backend Junior', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='outils_utilises',
            field=models.TextField(blank=True, help_text='Technologies utilisées durant la formation'),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='projets_realises',
            field=models.TextField(blank=True, help_text='Un projet réalisé par ligne'),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='salaire_haiti',
            field=models.CharField(blank=True, help_text='Ex : 40 000 à 120 000 HTG/mois', max_length=60),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='salaire_international',
            field=models.CharField(blank=True, help_text='Ex : 2 000 à 6 000 USD/mois', max_length=60),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='taux_employabilite',
            field=models.PositiveIntegerField(default=0, help_text='Pourcentage estimé'),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='temps_pour_emploi',
            field=models.CharField(blank=True, help_text='Ex : 3 à 6 mois', max_length=120),
        ),
        migrations.AlterField(
            model_name='formation',
            name='formation_upgrade',
            field=models.ForeignKey(blank=True, help_text='Formation premium recommandée après cette formation gratuite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_gratuites', to='academie.formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='gratuit',
            field=models.BooleanField(default=False, help_text='Formation gratuite (Lead Magnet)'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='illustration',
            field=models.CharField(blank=True, default='', help_text="Émoji d'illustration (💻 🤖 🔐 📈 ...)", max_length=10),
        ),
        migrations.AlterField(
            model_name='formation',
            name='message_partage',
            field=models.CharField(blank=True, default='', help_text='Message utilisé lors du partage automatique.', max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalformation',
            name='formation_upgrade',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Formation premium recommandée après cette formation gratuite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academie.formation'),
        ),
        migrations.AlterField(
            model_name='historicalformation',
            name='gratuit',
            field=models.BooleanField(default=False, help_text='Formation gratuite (Lead Magnet)'),
        ),
        migrations.AlterField(
            model_name='historicalformation',
            name='illustration',
            field=models.CharField(blank=True, default='', help_text="Émoji d'illustration (💻 🤖 🔐 📈 ...)", max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalformation',
            name='message_partage',
            field=models.CharField(blank=True, default='', help_text='Message utilisé lors du partage automatique.', max_length=500),
        ),
    ]
