# Generated by Django 6.0.7 on 2026-08-01 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0036_rename_resultat_projetetudiant_resultat_obtenu_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeTemoignage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("envoyee", "📤 Envoyée"),
                            ("repondue", "✍️ Répondue"),
                            ("consentement_donne", "✅ Consentement donné"),
                            ("validee_admin", "👍 Validée par admin"),
                            ("publiee", "🌐 Publiée"),
                            ("refusee", "❌ Refusée par le participant"),
                        ],
                        default="envoyee",
                        max_length=20,
                    ),
                ),
                ("reponse_texte", models.TextField(blank=True)),
                (
                    "note",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                ("consentement_publication", models.BooleanField(default=False)),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                ("date_reponse", models.DateTimeField(blank=True, null=True)),
                (
                    "formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academie.formation",
                    ),
                ),
                (
                    "temoignage_publie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academie.temoignage",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_temoignage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de témoignage",
                "verbose_name_plural": "Demandes de témoignage",
            },
        ),
    ]
