# Generated by Django 6.0.6 on 2026-07-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0036_formation_certification_obtenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('parent', 'Parent'), ('formateur', 'Formateur'), ('asst_formateur', 'Assistant Formateur'), ('resp_academique', 'Responsable Académique'), ('examinateur', 'Examinateur'), ('correcteur', 'Correcteur'), ('marketing', 'Marketing'), ('support', 'Support'), ('finance', 'Finance'), ('direction', 'Direction'), ('admin', 'Administrateur'), ('super_admin', 'Super Administrateur'), ('api_client', 'API Client')], default='etudiant', max_length=30),
        ),
    ]
