# Generated by Django 6.0.6 on 2026-07-13 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0037_profilutilisateur_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='bio_formateur',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='specialites',
            field=models.CharField(blank=True, help_text='Séparées par des virgules', max_length=300),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='taux_remuneration',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% des ventes reversé', max_digits=5),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='LogAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('validation_paiement', 'Validation de paiement'), ('suppression', 'Suppression'), ('modification_role', 'Modification de rôle'), ('remboursement', 'Remboursement'), ('publication', 'Publication de contenu'), ('connexion_admin', 'Connexion admin')], max_length=30)),
                ('description', models.TextField()),
                ('objet_type', models.CharField(blank=True, help_text='Ex: Order, Formation', max_length=100)),
                ('objet_id', models.IntegerField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-date_creation'],
            },
        ),
    ]
