# Generated by Django 6.0.7 on 2026-08-01 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0037_demandetemoignage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parrainage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("filleul_email", models.EmailField(max_length=254)),
                ("code_parrainage", models.CharField(editable=False, max_length=20, unique=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("invite", "📨 Invité"),
                            ("inscrit", "✅ Inscrit"),
                            ("actif", "🎯 Devenu actif"),
                        ],
                        default="invite",
                        max_length=15,
                    ),
                ),
                ("date_invitation", models.DateTimeField(auto_now_add=True)),
                ("date_conversion", models.DateTimeField(blank=True, null=True)),
                (
                    "filleul_utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parrainage_origine",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parrain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parrainages_envoyes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parrainage",
                "verbose_name_plural": "Parrainages",
            },
        ),
    ]
