# Generated by Django 6.0.6 on 2026-07-13 05:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0038_profilutilisateur_bio_formateur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='assigne_a',
            field=models.ForeignKey(blank=True, help_text="Membre de l'équipe responsable de ce lead", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscription',
            name='notes_internes',
            field=models.TextField(blank=True, help_text="Notes visibles uniquement par l'équipe"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='source_lead',
            field=models.CharField(blank=True, choices=[('site', 'Site web'), ('forum', 'Forum'), ('reseaux', 'Réseaux sociaux'), ('bouche_oreille', 'Bouche-à-oreille'), ('autre', 'Autre')], default='site', max_length=50),
        ),
        migrations.AddField(
            model_name='inscription',
            name='statut_lead',
            field=models.CharField(choices=[('nouveau', '🆕 Nouveau'), ('contacte', '📞 Contacté'), ('interesse', '💬 Intéressé'), ('converti', '✅ Converti'), ('perdu', '❌ Perdu')], default='nouveau', max_length=15),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
