# Generated by Django 6.0.6 on 2026-07-13 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0039_inscription_assigne_a_inscription_notes_internes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(choices=[('appel', '📞 Appel'), ('email', '📧 Email'), ('whatsapp', '💬 WhatsApp'), ('rencontre', '🤝 Rencontre'), ('note', '📝 Note')], default='note', max_length=15)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='academie.inscription')),
            ],
            options={
                'verbose_name': 'Interaction CRM',
                'verbose_name_plural': 'Interactions CRM',
                'ordering': ['-date_creation'],
            },
        ),
    ]
