# Generated by Django 6.0.7 on 2026-08-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0039_formation_criteres_evaluation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "type_partenaire",
                    models.CharField(
                        choices=[
                            ("entreprise", "🏢 Entreprise"),
                            ("institution", "🏛️ Institution"),
                            ("ong", "🤝 ONG"),
                            ("media", "📰 Média"),
                        ],
                        default="entreprise",
                        max_length=15,
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="partenaires/logos/")),
                ("description", models.CharField(blank=True, max_length=250)),
                ("url_site", models.URLField(blank=True)),
                ("actif", models.BooleanField(default=True)),
                ("ordre", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
                "ordering": ["ordre"],
            },
        ),
    ]
