# Generated by Django 6.0.6 on 2026-07-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0040_interactioncrm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('actif', '✅ Actif'), ('en_attente', '⏳ En attente validation'), ('suspendu', '⛔ Suspendu')], default='en_attente', max_length=15)),
                ('date_recrutement', models.DateTimeField(auto_now_add=True)),
                ('numero_contrat', models.CharField(blank=True, max_length=50)),
                ('document_cv', models.FileField(blank=True, null=True, upload_to='enseignants/cv/')),
                ('formations_attribuees', models.ManyToManyField(blank=True, related_name='enseignants', to='academie.formation')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to='academie.profilutilisateur')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
    ]
