# Generated by Django 6.0.7 on 2026-08-01 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0040_partenaire"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ambassadeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("pilote", "🚀 Pilote fondateur"),
                            ("actif", "⭐ Ambassadeur actif"),
                            ("elite", "🏆 Ambassadeur élite"),
                        ],
                        default="pilote",
                        max_length=15,
                    ),
                ),
                (
                    "citation_mise_en_avant",
                    models.CharField(
                        blank=True, help_text="Phrase courte affichée publiquement", max_length=250
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="ambassadeurs/")),
                (
                    "visible_publiquement",
                    models.BooleanField(
                        default=False, help_text="Nécessite le consentement explicite"
                    ),
                ),
                ("date_nomination", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statut_ambassadeur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ambassadeur",
                "verbose_name_plural": "Ambassadeurs",
            },
        ),
    ]
