# Generated by Django 6.0.6 on 2026-07-14 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0041_enseignant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accesformationdebloque',
            index=models.Index(fields=['utilisateur'], name='academie_ac_utilisa_8555a8_idx'),
        ),
        migrations.AddIndex(
            model_name='accesformationdebloque',
            index=models.Index(fields=['formation'], name='academie_ac_formati_2b5639_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['statut', 'date_creation'], name='academie_or_statut_0b234d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['utilisateur', 'statut'], name='academie_or_utilisa_cbea9d_idx'),
        ),
        migrations.AddIndex(
            model_name='progressionlecon',
            index=models.Index(fields=['utilisateur', 'terminee'], name='academie_pr_utilisa_09e569_idx'),
        ),
        migrations.AddIndex(
            model_name='progressionlecon',
            index=models.Index(fields=['lecon', 'terminee'], name='academie_pr_lecon_i_d94662_idx'),
        ),
        migrations.AddIndex(
            model_name='sujet',
            index=models.Index(fields=['categorie', 'date_creation'], name='academie_su_categor_a8dcbb_idx'),
        ),
        migrations.AddIndex(
            model_name='sujet',
            index=models.Index(fields=['formation'], name='academie_su_formati_e4eaae_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['statut'], name='academie_tr_statut_bd45aa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['commande', 'statut'], name='academie_tr_command_9cfd95_idx'),
        ),
    ]
