# Generated by Django 6.0.7 on 2026-08-02 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0041_ambassadeur"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtudeDeCas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("probleme", models.TextField(help_text="Problème posé")),
                ("solution", models.TextField(help_text="Solution apportée")),
                ("resultat", models.TextField(blank=True, help_text="Résultat concret obtenu")),
                (
                    "difficulte",
                    models.CharField(
                        choices=[
                            ("debutant", "🌱 Débutant"),
                            ("intermediaire", "⚡ Intermédiaire"),
                            ("avance", "🔥 Avancé"),
                        ],
                        default="intermediaire",
                        max_length=15,
                    ),
                ),
                ("ordre", models.IntegerField(default=0)),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etudes_de_cas",
                        to="academie.formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étude de cas",
                "verbose_name_plural": "Études de cas",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Outil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=150, unique=True)),
                ("icone", models.CharField(default="🛠️", max_length=10)),
                ("description", models.TextField(blank=True)),
                ("ordre", models.IntegerField(default=0)),
                (
                    "formations",
                    models.ManyToManyField(
                        blank=True, related_name="outils_enseignes", to="academie.formation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Outil / Logiciel",
                "verbose_name_plural": "Outils / Logiciels",
                "ordering": ["ordre", "nom"],
            },
        ),
    ]
