# Generated by Django 6.0.6 on 2026-07-14 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0042_accesformationdebloque_academie_ac_utilisa_8555a8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_actuel', models.CharField(choices=[('brouillon', '📝 Brouillon'), ('en_revision', '🔍 En révision'), ('validee', '✅ Validée — prête à publier'), ('publiee', '🌐 Publiée'), ('suspendue', '⏸️ Suspendue temporairement'), ('archivee', '📦 Archivée')], default='brouillon', max_length=20)),
                ('checklist_contenu_complet', models.BooleanField(default=False, help_text='Modules et leçons rédigés')),
                ('checklist_seo_complet', models.BooleanField(default=False, help_text='Description et mots-clés renseignés')),
                ('checklist_prix_valide', models.BooleanField(default=False, help_text='Prix et promotions vérifiés')),
                ('checklist_quiz_present', models.BooleanField(default=False, help_text='Au moins un quiz créé')),
                ('commentaire_revision', models.TextField(blank=True, help_text='Retours du réviseur si refus')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_transition', models.DateTimeField(auto_now=True)),
                ('demande_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_demandes', to=settings.AUTH_USER_MODEL)),
                ('formation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='academie.formation')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow de formation',
                'verbose_name_plural': 'Workflows de formations',
            },
        ),
    ]
