# Generated by Django 6.0.7 on 2026-08-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0043_etudedecas_outil"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecole",
            name="description_courte",
            field=models.CharField(
                blank=True, help_text="Phrase d'accroche pour la page Nos Écoles", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="ecole",
            name="est_ecole_phare",
            field=models.BooleanField(
                default=False,
                help_text="Écoles à mettre en avant dans la navigation, le SEO et la page d'accueil (IA, Dev, Logistique)",
            ),
        ),
    ]
