# Generated by Django 6.0.6 on 2026-07-16 00:37

import django.db.models.deletion
import django_ckeditor_5.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0043_workflowformation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affilie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_affiliation', models.CharField(max_length=20, unique=True)),
                ('taux_commission', models.DecimalField(decimal_places=2, default=10, help_text='% de commission', max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affilié',
                'verbose_name_plural': 'Affiliés',
            },
        ),
        migrations.CreateModel(
            name='CommissionAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée')], default='en_attente', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('affilie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='academie.affilie')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academie.order')),
            ],
            options={
                'verbose_name': 'Commission affiliation',
                'verbose_name_plural': 'Commissions affiliation',
            },
        ),
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('resume', models.TextField(max_length=500)),
                ('contenu', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('categorie', models.CharField(choices=[('guide', '📖 Guide'), ('tutoriel', '🎓 Tutoriel'), ('actualite', '📰 Actualité'), ('conseil', '💡 Conseil'), ('outil', '🛠️ Outil')], default='guide', max_length=20)),
                ('en_vedette', models.BooleanField(default=False)),
                ('publie', models.BooleanField(default=False)),
                ('temps_lecture', models.IntegerField(default=5, help_text='Temps de lecture estimé en minutes')),
                ('date_publication', models.DateTimeField(blank=True, editable=False)),
                ('date_modification', models.DateTimeField(blank=True, editable=False)),
                ('meta_titre', models.CharField(blank=True, help_text='Titre SEO (60-70 caractères recommandés)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Description SEO (150-160 caractères recommandés)', max_length=160)),
                ('mots_cles', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=255)),
                ('noindex', models.BooleanField(default=False, help_text="Empêcher l'indexation Google")),
                ('type_contenu', models.CharField(choices=[('article', '📝 Article'), ('guide', '📖 Guide'), ('tutoriel', '🎓 Tutoriel'), ('etude_cas', '📊 Étude de cas'), ('actualite', '📰 Actualité Tech'), ('livre_blanc', '📄 Livre blanc'), ('faq', '❓ FAQ')], default='article', max_length=20)),
                ('fichier_telechargeable', models.TextField(blank=True, max_length=100, null=True)),
                ('nb_vues', models.IntegerField(default=0)),
                ('nb_partages', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('auteur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('formation_liee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academie.formation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Article',
                'verbose_name_plural': 'historical Articles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
