# Generated by Django 6.0.7 on 2026-08-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0044_ecole_description_courte_ecole_est_ecole_phare"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcours",
            name="metiers_vises",
            field=models.TextField(blank=True, help_text="Métiers visés par ce parcours"),
        ),
        migrations.AddField(
            model_name="parcours",
            name="projets_inclus",
            field=models.TextField(
                blank=True, help_text="Projets concrets inclus dans le parcours"
            ),
        ),
    ]
