# Generated by Django 6.0.6 on 2026-07-16 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0044_affilie_commissionaffiliation_historicalarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='affilie_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_generees', to='academie.affilie'),
        ),
    ]
