# Generated by Django 6.0.6 on 2026-07-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0045_order_affilie_origine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('sous_titre', models.CharField(blank=True, help_text="Ex: L'école de la haute technologie moderne d'Haïti", max_length=250)),
                ('icone', models.CharField(default='🎓', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='academies/logos/')),
                ('couleur_principale', models.CharField(default='#0B2447', max_length=7)),
                ('couleur_accent', models.CharField(default='#00B4D8', max_length=7)),
                ('domaine_personnalise', models.CharField(blank=True, help_text='Ex: business.blessytechacademy.com (optionnel — sous-domaine dédié)', max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('est_academie_par_defaut', models.BooleanField(default=False, help_text='Une seule Academie doit avoir ce champ à True — utilisée en fallback')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Académie',
                'verbose_name_plural': 'Académies',
                'ordering': ['nom'],
            },
        ),
    ]
