# Generated by Django 6.0.7 on 2026-08-02 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0045_parcours_metiers_vises_parcours_projets_inclus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outil",
            options={
                "ordering": ["nom"],
                "verbose_name": "Outil pédagogique",
                "verbose_name_plural": "Outils pédagogiques",
            },
        ),
        migrations.RemoveField(
            model_name="outil",
            name="description",
        ),
        migrations.RemoveField(
            model_name="outil",
            name="ordre",
        ),
        migrations.AddField(
            model_name="etudedecas",
            name="contexte",
            field=models.TextField(
                blank=True, help_text="Situation professionnelle réelle ou réaliste"
            ),
        ),
        migrations.AddField(
            model_name="etudedecas",
            name="module_lie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academie.module",
            ),
        ),
        migrations.AddField(
            model_name="etudedecas",
            name="objectif",
            field=models.TextField(
                blank=True, help_text="Ce que l'étudiant doit résoudre/produire"
            ),
        ),
        migrations.AddField(
            model_name="outil",
            name="site_officiel",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="parcours",
            name="certifications_incluses",
            field=models.TextField(
                blank=True, help_text="Certifications délivrées durant le parcours"
            ),
        ),
        migrations.AlterField(
            model_name="outil",
            name="nom",
            field=models.CharField(max_length=100),
        ),
    ]
