# Generated by Django 6.0.6 on 2026-07-16 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0046_academie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='academie',
            field=models.ForeignKey(blank=True, help_text='Académie mère de cette école', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecoles', to='academie.academie'),
        ),
        migrations.AddField(
            model_name='historicalecole',
            name='academie',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Académie mère de cette école', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academie.academie'),
        ),
    ]
