# Generated by Django 6.0.7 on 2026-08-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0046_alter_outil_options_remove_outil_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examen",
            name="actif",
            field=models.BooleanField(default=True),
        ),
    ]
