# Generated by Django 6.0.7 on 2026-08-02 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0047_examen_actif"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("webinaire", "🎥 Webinaire"),
                            ("hackathon", "💻 Hackathon"),
                            ("atelier", "🛠️ Atelier"),
                            ("remise_certificats", "🎓 Remise de certificats"),
                        ],
                        default="webinaire",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("lien_inscription", models.URLField(blank=True)),
                ("lien_visio", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="evenements/")),
                ("publie", models.BooleanField(default=False)),
                (
                    "formation_liee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academie.formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["date_debut"],
            },
        ),
    ]
