# Generated by Django 6.0.6 on 2026-07-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0047_ecole_academie_historicalecole_academie'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='academies',
            field=models.ManyToManyField(blank=True, help_text='Académies auxquelles cet utilisateur a accès (étudiant multi-académie ou formateur multi-académie)', related_name='membres', to='academie.academie'),
        ),
    ]
