# Generated by Django 6.0.7 on 2026-08-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0048_evenement"),
    ]

    operations = [
        migrations.AddField(
            model_name="formation",
            name="badge_associe",
            field=models.CharField(blank=True, help_text="Badge attribué à 100%", max_length=100),
        ),
    ]
