# Generated by Django 6.0.6 on 2026-07-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0048_profilutilisateur_academies'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartenaireAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email_contact', models.EmailField(max_length=254)),
                ('cle_api', models.CharField(max_length=64, unique=True)),
                ('type_partenaire', models.CharField(choices=[('universite', 'Université'), ('entreprise', 'Entreprise'), ('ong', 'ONG'), ('gouvernement', 'Gouvernement')], default='entreprise', max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partenaire API',
                'verbose_name_plural': 'Partenaires API',
            },
        ),
    ]
