# Generated by Django 6.0.7 on 2026-08-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0049_formation_badge_associe"),
    ]

    operations = [
        migrations.AddField(
            model_name="formation",
            name="delivre_certificat",
            field=models.BooleanField(
                default=True, help_text="Cocher si cette formation délivre un certificat"
            ),
        ),
    ]
