# Generated by Django 6.0.6 on 2026-07-16 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0049_partenaireapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaireapi',
            name='academie_associee',
            field=models.ForeignKey(blank=True, help_text="Si défini, ce partenaire n'accède qu'aux données de cette académie. Vide = accès toutes académies.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partenaires_api', to='academie.academie'),
        ),
    ]
