# Generated by Django 6.0.7 on 2026-08-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0050_formation_delivre_certificat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formation",
            name="duree_mois",
        ),
        migrations.AddField(
            model_name="formation",
            name="duree",
            field=models.IntegerField(default=1, help_text="Valeur numérique de la durée"),
        ),
        migrations.AddField(
            model_name="formation",
            name="duree_unite",
            field=models.CharField(
                choices=[("heures", "Heures"), ("jours", "Jours"), ("mois", "Mois")],
                default="mois",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="formation",
            name="niveau",
            field=models.CharField(
                choices=[
                    ("debutant", "Débutant"),
                    ("intermediaire", "Intermédiaire"),
                    ("avance", "Avancé"),
                    ("professionnel", "Professionnel"),
                    ("expert", "Expert"),
                    ("debutant_avance", "Débutant → Avancé"),
                    ("intermediaire_expert", "Intermédiaire → Expert"),
                ],
                default="debutant",
                max_length=30,
            ),
        ),
    ]
