# Generated by Django 6.0.7 on 2026-08-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0051_remove_formation_duree_mois_formation_duree_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formation",
            name="duree_unite",
            field=models.CharField(
                choices=[
                    ("heures", "Heures"),
                    ("jours", "Jours"),
                    ("semaines", "Semaines"),
                    ("mois", "Mois"),
                ],
                default="mois",
                max_length=10,
            ),
        ),
    ]
