# Generated by Django 6.0.7 on 2026-08-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0052_alter_formation_duree_unite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcours",
            name="duree_mois",
        ),
        migrations.AddField(
            model_name="parcours",
            name="duree",
            field=models.IntegerField(default=12, help_text="Valeur numérique de la durée"),
        ),
        migrations.AddField(
            model_name="parcours",
            name="duree_unite",
            field=models.CharField(
                choices=[
                    ("heures", "Heures"),
                    ("jours", "Jours"),
                    ("semaines", "Semaines"),
                    ("mois", "Mois"),
                ],
                default="mois",
                max_length=10,
            ),
        ),
    ]
