# Generated by Django 6.0.7 on 2026-08-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0053_remove_parcours_duree_mois_parcours_duree_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecon",
            name="contenu",
            field=models.TextField(
                blank=True,
                help_text="Contenu complet de la leçon — CKEditor : texte, images, code, tableaux",
            ),
        ),
        migrations.AlterField(
            model_name="lecon",
            name="resume",
            field=models.TextField(
                blank=True, help_text="1-2 phrases — apparaît dans le programme de la formation"
            ),
        ),
    ]
