# Generated by Django 6.0.7 on 2026-08-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0054_alter_lecon_contenu_alter_lecon_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcours",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
