# Generated by Django 6.0.7 on 2026-08-04 16:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0055_parcours_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificat",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Identifiant universel public pour la vérification",
                unique=True,
            ),
        ),
    ]
