# Generated by Django 6.0.7 on 2026-08-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0056_add_uuid_to_certificat"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificat",
            name="date_revocation",
            field=models.DateTimeField(
                blank=True, help_text="Date de révocation (si révoqué)", null=True
            ),
        ),
        migrations.AddField(
            model_name="certificat",
            name="hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 du contenu du certificat pour vérification d'intégrité",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certificat",
            name="raison_revocation",
            field=models.TextField(blank=True, help_text="Raison de la révocation", null=True),
        ),
        migrations.AlterField(
            model_name="certificat",
            name="numero",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Numéro lisible (ex: BTA-2026-PRO-0001)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="certificat",
            name="verifie",
            field=models.BooleanField(
                default=False, help_text="Indique si le certificat a été vérifié publiquement"
            ),
        ),
    ]
