# Generated by Django 6.0.7 on 2026-08-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0057_add_hash_and_revocation_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificat",
            options={
                "permissions": [
                    ("can_generate_certificat", "Peut générer un certificat"),
                    ("can_revoke_certificat", "Peut révoquer un certificat"),
                ],
                "verbose_name": "Certificat",
                "verbose_name_plural": "Certificats",
            },
        ),
        migrations.AlterModelOptions(
            name="formation",
            options={
                "permissions": [
                    ("view_formation_detail", "Peut voir le détail d'une formation"),
                    ("edit_formation", "Peut modifier une formation"),
                    ("can_delete_formation", "Peut supprimer une formation"),
                    ("publish_formation", "Peut publier une formation"),
                    (
                        "manage_formation_content",
                        "Peut gérer le contenu d'une formation (modules, leçons)",
                    ),
                    ("view_formation_stats", "Peut voir les statistiques d'une formation"),
                ],
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
            },
        ),
    ]
