# Generated by Django 6.0.7 on 2026-08-06 03:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0058_fix_certificat_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificatHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("valide", "✅ Valide"),
                            ("revoque", "❌ Révoqué"),
                            ("expire", "⏳ Expiré"),
                        ],
                        max_length=15,
                    ),
                ),
                ("raison", models.TextField(blank=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "certificat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="academie.certificat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique certificat",
                "verbose_name_plural": "Historique certificats",
                "db_table": "academie_certificathistorique",
                "ordering": ["-date"],
            },
        ),
    ]
