# Generated by Django 6.0.7 on 2026-08-06 03:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0059_certificathistorique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_inscription", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("achat", "Achat"),
                            ("gratuit", "Offre gratuite"),
                            ("parrainage", "Parrainage"),
                            ("admin", "Attribution admin"),
                            ("promotion", "Campagne promotionnelle"),
                        ],
                        default="achat",
                        max_length=20,
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academie.order",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="academie.formation",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "db_table": "academie_enrollment",
                "unique_together": {("utilisateur", "formation")},
            },
        ),
    ]
