# Generated by Django 6.0.7 on 2026-08-06 03:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0060_enrollment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certificat",
            name="revoque_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificats_revoques",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="certificat",
            name="hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 du contenu du certificat pour vérification d'intégrité (équivalent à hash_preuve)",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="certificat",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Identifiant universel public pour la vérification (équivalent à public_id)",
                unique=True,
            ),
        ),
    ]
