# Generated by Django 6.0.7 on 2026-08-06 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0061_certificat_revoque_par_alter_certificat_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificat",
            name="hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 du contenu du certificat pour vérification d'intégrité",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="certificat",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Identifiant universel public pour la vérification",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="RegistreEmissionCertificat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("emission", "✅ Émission"),
                            ("revocation", "❌ Révocation"),
                            ("verification_externe", "🔍 Vérification consultée"),
                        ],
                        max_length=25,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("date_evenement", models.DateTimeField(auto_now_add=True)),
                (
                    "certificat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registre",
                        to="academie.certificat",
                    ),
                ),
                (
                    "effectue_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registre d'émission certificat",
                "verbose_name_plural": "Registre d'émission certificats",
                "db_table": "academie_registre_emission_certificat",
                "ordering": ["date_evenement"],
            },
        ),
    ]
