# Generated by Django 6.0.7 on 2026-08-06 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0062_alter_certificat_hash_alter_certificat_uuid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "Inscription (Enrollment)",
                "verbose_name_plural": "Inscriptions (Enrollments)",
            },
        ),
        migrations.RenameField(
            model_name="enrollment",
            old_name="commande",
            new_name="commande_origine",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="source",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="accorde_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments_accordes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="cohorte_origine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academie.cohorte",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="date_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="origine",
            field=models.CharField(
                choices=[
                    ("achat", "💰 Achat payant"),
                    ("gratuit", "🎁 Formation gratuite"),
                    ("cohorte", "👥 Cohorte pilote"),
                    ("offert_admin", "🎟️ Offert par admin"),
                    ("parcours", "🚀 Inclus dans un parcours"),
                ],
                default="achat",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="statut",
            field=models.CharField(
                choices=[
                    ("actif", "✅ Actif"),
                    ("suspendu", "⏸️ Suspendu"),
                    ("termine", "🏁 Terminé"),
                    ("expire", "⏳ Expiré"),
                ],
                default="actif",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="date_inscription",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["utilisateur", "statut"], name="academie_en_utilisa_eb0f1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["formation", "statut"], name="academie_en_formati_ceb74b_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="enrollment",
            table=None,
        ),
    ]
