# Generated by Django 6.0.7 on 2026-08-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0063_alter_enrollment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="competences_liees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Compétences validées si l'étudiant réussit ce quiz (évaluations sommatives/finales)",
                related_name="quiz_lies",
                to="academie.competence",
            ),
        ),
    ]
