# Generated by Django 6.0.7 on 2026-08-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0064_quiz_competences_liees"),
    ]

    operations = [
        migrations.AddField(
            model_name="partenaireapi",
            name="scopes",
            field=models.JSONField(
                default=list,
                help_text="Liste des permissions accordées à ce partenaire, ex: ['formations.lire']",
            ),
        ),
    ]
