# Generated by Django 6.0.7 on 2026-08-06 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0067_partenaireapi_date_expiration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="relu_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles_relus",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="statut_editorial",
            field=models.CharField(
                choices=[
                    ("brouillon", "📝 Brouillon"),
                    ("en_relecture", "🔍 En relecture"),
                    ("publie", "🌐 Publié"),
                    ("archive", "📦 Archivé"),
                ],
                default="brouillon",
                max_length=15,
            ),
        ),
    ]
