# Generated by Django 6.0.7 on 2026-08-06 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0068_article_relu_par_article_statut_editorial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibiliteCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "frais_paye",
                    models.BooleanField(
                        default=False, help_text="Frais de certification acquittés"
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "certificat_genere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eligibilite_origine",
                        to="academie.certificat",
                    ),
                ),
                (
                    "cohorte",
                    models.ForeignKey(
                        help_text="Ce processus contrôlé (frais + validation admin) s'applique UNIQUEMENT aux membres d'une cohorte",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibilites_certification",
                        to="academie.cohorte",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibilites_certification",
                        to="academie.formation",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibilites_certification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications_validees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Éligibilité certification",
                "verbose_name_plural": "Éligibilités certifications",
                "db_table": "academie_eligibilitecertification",
                "unique_together": {("utilisateur", "formation")},
            },
        ),
    ]
