# Generated by Django 6.0.7 on 2026-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0069_eligibilitecertification"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohorte",
            name="frais_montant",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant des frais de certification en USD",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="eligibilitecertification",
            name="moyenne_finale",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Moyenne pondérée ou simple des notes",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eligibilitecertification",
            name="note_projet",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Note du projet sur 100",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eligibilitecertification",
            name="note_theorique",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Note de l'examen théorique sur 100",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eligibilitecertification",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_cours", "En cours"),
                    ("eligible", "Éligible (certificat prêt)"),
                    ("certifie", "Certifié"),
                    ("refuse", "Refusé"),
                ],
                default="en_cours",
                max_length=10,
            ),
        ),
    ]
