# Generated by Django 6.0.7 on 2026-08-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0070_cohorte_frais_montant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificat",
            name="parcours_origine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificats_delivres",
                to="academie.parcours",
            ),
        ),
    ]
