# Generated by Django 6.0.7 on 2026-08-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0071_certificat_parcours_origine"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilutilisateur",
            name="consentement_profil_public",
            field=models.BooleanField(
                default=False,
                help_text="Autorise l'affichage public de témoignage+certificat+portfolio+badges réunis",
            ),
        ),
    ]
