# Generated by Django 6.0.7 on 2026-08-06 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0072_profilutilisateur_consentement_profil_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleBanque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(help_text="Ex: INT, IA, BUR, STK", max_length=10, unique=True),
                ),
                ("icone", models.CharField(default="📚", max_length=10)),
                (
                    "hors_examen_principal",
                    models.BooleanField(default=False, help_text="Ex: Gestion de Stock = bonus"),
                ),
                ("ordre", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Module (Banque)",
                "verbose_name_plural": "Modules (Banque)",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="GabaritExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("duree_minutes", models.IntegerField(default=90)),
                ("seuil_reussite", models.IntegerField(default=70)),
                ("actif", models.BooleanField(default=True)),
                (
                    "formation_liee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academie.formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gabarit d'examen",
                "verbose_name_plural": "Gabarits d'examen",
            },
        ),
        migrations.CreateModel(
            name="ExamenGenere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "⏳ En cours"),
                            ("termine", "✅ Terminé"),
                            ("abandonne", "❌ Abandonné"),
                        ],
                        default="en_cours",
                        max_length=15,
                    ),
                ),
                ("date_debut", models.DateTimeField(auto_now_add=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "score_brut",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "score_pourcentage",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("reussi", models.BooleanField(null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examens_banque",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gabarit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="examens_generes",
                        to="academie.gabaritexamen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen généré (Banque)",
                "verbose_name_plural": "Examens générés (Banque)",
            },
        ),
        migrations.CreateModel(
            name="CompositionGabarit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("facile", "🟢 Facile"),
                            ("intermediaire", "🟡 Intermédiaire"),
                            ("avance", "🟠 Avancé"),
                            ("professionnel", "🔴 Professionnel"),
                        ],
                        help_text="Vide = tous niveaux",
                        max_length=15,
                    ),
                ),
                ("nombre_questions", models.IntegerField(default=10)),
                (
                    "points_par_question",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "gabarit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composition",
                        to="academie.gabaritexamen",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academie.modulebanque"
                    ),
                ),
            ],
            options={
                "verbose_name": "Composition du gabarit",
                "verbose_name_plural": "Compositions du gabarit",
            },
        ),
        migrations.CreateModel(
            name="CategorieBanque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("ordre", models.IntegerField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="academie.modulebanque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie (Banque)",
                "verbose_name_plural": "Catégories (Banque)",
                "ordering": ["module", "ordre"],
                "unique_together": {("module", "nom")},
            },
        ),
        migrations.CreateModel(
            name="QuestionBanque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "identifiant_unique",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Ex: INT-NAV-0001",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("facile", "🟢 Facile"),
                            ("intermediaire", "🟡 Intermédiaire"),
                            ("avance", "🟠 Avancé"),
                            ("professionnel", "🔴 Professionnel"),
                        ],
                        default="intermediaire",
                        max_length=15,
                    ),
                ),
                (
                    "type_question",
                    models.CharField(
                        choices=[
                            ("qcm", "QCM (une seule bonne réponse)"),
                            ("choix_multiples", "Choix multiples (plusieurs bonnes réponses)"),
                            ("vrai_faux", "Vrai / Faux"),
                            ("association", "Association (relier des éléments)"),
                            ("classement", "Classement (ordonner des éléments)"),
                            ("completer", "Compléter une phrase"),
                            ("reponse_courte", "Réponse courte (texte libre)"),
                            ("etude_cas", "Étude de cas"),
                            ("analyse_image", "Analyse d'image / capture d'écran"),
                            ("scenario_pro", "Scénario professionnel"),
                            ("analyse_prompt_ia", "Prompt IA à analyser"),
                            ("correction_word", "Document Word à corriger"),
                            ("analyse_excel", "Feuille Excel à analyser"),
                            ("amelioration_ppt", "Présentation PowerPoint à améliorer"),
                        ],
                        default="qcm",
                        max_length=25,
                    ),
                ),
                ("enonce", models.TextField(help_text="Le texte de la question")),
                (
                    "illustration",
                    models.ImageField(
                        blank=True, null=True, upload_to="banque_questions/illustrations/"
                    ),
                ),
                (
                    "fichier_support",
                    models.FileField(
                        blank=True,
                        help_text="Document Word/Excel/PPT à analyser si applicable",
                        null=True,
                        upload_to="banque_questions/fichiers/",
                    ),
                ),
                (
                    "reponses_possibles",
                    models.JSONField(
                        default=list,
                        help_text='QCM: [{"texte": "...", "correct": true}]. Association: [{"gauche": "...", "droite": "..."}]. Classement: ["étape1", "étape2"...]',
                    ),
                ),
                (
                    "reponse_texte_courte",
                    models.CharField(
                        blank=True,
                        help_text="Pour type 'reponse_courte' — réponse(s) acceptée(s), séparées par |",
                        max_length=300,
                    ),
                ),
                (
                    "explication_pedagogique",
                    models.TextField(help_text="Affichée APRÈS soumission, jamais avant"),
                ),
                (
                    "reference_cours",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Formation Bureautique — Module 3, Leçon 2",
                        max_length=200,
                    ),
                ),
                (
                    "mots_cles",
                    models.CharField(
                        blank=True,
                        help_text="Séparés par des virgules — pour la recherche",
                        max_length=300,
                    ),
                ),
                ("temps_conseille_secondes", models.IntegerField(default=90)),
                ("points_base", models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "📝 Brouillon"),
                            ("active", "✅ Active"),
                            ("archivee", "📦 Archivée"),
                            ("en_revision", "🔍 En révision"),
                        ],
                        default="brouillon",
                        max_length=15,
                    ),
                ),
                ("version", models.IntegerField(default=1, editable=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="academie.categoriebanque",
                    ),
                ),
                (
                    "competence_evaluee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_banque",
                        to="academie.competence",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="academie.modulebanque",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_validees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Question (Banque)",
                "verbose_name_plural": "Questions (Banque)",
            },
        ),
        migrations.CreateModel(
            name="QuestionExamenGenere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordre", models.IntegerField()),
                (
                    "reponses_ordre_affiche",
                    models.JSONField(
                        default=list, help_text="Snapshot des réponses mélangées pour CET étudiant"
                    ),
                ),
                (
                    "points_attribues",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions_ordonnees",
                        to="academie.examengenere",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academie.questionbanque"
                    ),
                ),
            ],
            options={
                "ordering": ["ordre"],
                "unique_together": {("examen", "question")},
            },
        ),
        migrations.AddField(
            model_name="examengenere",
            name="questions_tirees",
            field=models.ManyToManyField(
                through="academie.QuestionExamenGenere", to="academie.questionbanque"
            ),
        ),
        migrations.CreateModel(
            name="ReponseEtudiantBanque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "points_attribues",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "reponse_donnee",
                    models.JSONField(default=dict, help_text="Format libre selon type_question"),
                ),
                ("est_correcte", models.BooleanField(default=False)),
                ("temps_pris_secondes", models.IntegerField(default=0)),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses_donnees",
                        to="academie.examengenere",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academie.questionbanque"
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse étudiant (Banque)",
                "verbose_name_plural": "Réponses étudiants (Banque)",
            },
        ),
        migrations.CreateModel(
            name="SousCategorieBanque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_categories",
                        to="academie.categoriebanque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-catégorie (Banque)",
                "verbose_name_plural": "Sous-catégories (Banque)",
            },
        ),
        migrations.AddField(
            model_name="questionbanque",
            name="sous_categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="academie.souscategoriebanque",
            ),
        ),
        migrations.CreateModel(
            name="StatistiqueQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nb_utilisations", models.IntegerField(default=0)),
                ("nb_reussites", models.IntegerField(default=0)),
                ("temps_moyen_secondes", models.FloatField(default=0)),
                ("derniere_maj", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistiques",
                        to="academie.questionbanque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistique de question",
                "verbose_name_plural": "Statistiques de questions",
            },
        ),
        migrations.CreateModel(
            name="VersionQuestionBanque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("numero_version", models.IntegerField()),
                (
                    "contenu_snapshot",
                    models.JSONField(
                        help_text="Snapshot complet des champs au moment de cette version"
                    ),
                ),
                ("date_modification", models.DateTimeField(auto_now_add=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_versions",
                        to="academie.questionbanque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version de question",
                "verbose_name_plural": "Versions de questions",
                "ordering": ["-numero_version"],
            },
        ),
        migrations.AddIndex(
            model_name="examengenere",
            index=models.Index(
                fields=["utilisateur", "statut"], name="academie_ex_utilisa_fe7326_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reponseetudiantbanque",
            unique_together={("examen", "question")},
        ),
        migrations.AddIndex(
            model_name="questionbanque",
            index=models.Index(
                fields=["module", "niveau", "statut"], name="academie_qu_module__741e39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionbanque",
            index=models.Index(
                fields=["categorie", "statut"], name="academie_qu_categor_d0f8bc_idx"
            ),
        ),
    ]
