# Generated by Django 6.0.7 on 2026-08-07 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0073_modulebanque_gabaritexamen_examengenere_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gabaritexamen",
            name="cohorte_pilote",
            field=models.ForeignKey(
                blank=True,
                help_text="Si défini, ce gabarit est en phase de TEST avec cette cohorte avant généralisation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gabarits_test",
                to="academie.cohorte",
            ),
        ),
        migrations.AddField(
            model_name="gabaritexamen",
            name="phase_test",
            field=models.BooleanField(
                default=False,
                help_text="Active le mode test — statistiques suivies de près pour ajustement",
            ),
        ),
    ]
