# Generated by Django 6.0.7 on 2026-08-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0074_gabaritexamen_cohorte_pilote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbanque",
            name="commentaire_revision",
            field=models.TextField(
                blank=True,
                help_text="Notes sur pourquoi cette question a été signalée/ajustée suite au test pilote",
            ),
        ),
        migrations.AddField(
            model_name="questionbanque",
            name="signalee_ambigue",
            field=models.BooleanField(
                default=False,
                help_text="Marquée par un apprenant ou l'admin comme potentiellement ambiguë",
            ),
        ),
    ]
