# Generated by Django 6.0.7 on 2026-08-08 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0075_questionbanque_commentaire_revision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriebanque",
            name="competence_associee",
            field=models.ForeignKey(
                blank=True,
                help_text="Compétence validée automatiquement si l'étudiant réussit une question de cette catégorie",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories_banque",
                to="academie.competence",
            ),
        ),
    ]
