# Generated by Django 6.0.7 on 2026-08-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0076_categoriebanque_competence_associee"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificat",
            name="formations_incluses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Liste des formations couvertes par ce certificat (ex: pour un parcours ou une cohorte)",
                related_name="certificats_inclus_dans",
                to="academie.formation",
            ),
        ),
        migrations.AddField(
            model_name="certificat",
            name="libelle_programme",
            field=models.CharField(
                blank=True,
                help_text="Ex: Compétences Numériques Professionnelles – Programme Fondateur",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="certificat",
            name="mention",
            field=models.CharField(
                blank=True,
                help_text="Ex: Très Bien, Bien, Assez Bien, Félicitations",
                max_length=50,
            ),
        ),
    ]
