# Generated by Django 6.0.7 on 2026-08-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0077_certificat_formations_incluses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eligibilitecertification",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_cours", "En cours"),
                    ("eligible", "Éligible (certificat prêt)"),
                    ("certificat_pret", "Certificat prêt au téléchargement"),
                    ("certificat_delivre", "Certificat délivré"),
                    ("certifie", "Certifié"),
                    ("refuse", "Refusé"),
                ],
                default="en_cours",
                max_length=20,
            ),
        ),
    ]
