# Generated by Django 6.0.7 on 2026-08-08 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academie", "0078_alter_eligibilitecertification_statut"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="academie_tr_statut_bd45aa_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="academie_tr_command_9cfd95_idx",
        ),
        migrations.AddField(
            model_name="eligibilitecertification",
            name="transaction_certification_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID de la transaction billing.Transaction liée au paiement (MonCash/NatCash)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eligibilitecertification",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_cours", "En cours"),
                    ("eligible", "Éligible (certificat prêt)"),
                    ("certificat_pret", "Certificat prêt au téléchargement"),
                    ("certificat_delivre", "Certificat délivré"),
                    ("certifie", "Certifié"),
                    ("refuse", "Refusé"),
                    ("paiement_en_attente", "Paiement en attente de vérification"),
                ],
                default="en_cours",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="commande",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="academie.order",
            ),
        ),
    ]
